Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2018-12, with the labels that each got.

#771 BigQuery: Fix extract table sample
  bigquery/api/src/extract_table.php
  bigquery/api/test/bigqueryTest.php
Labels: bug

#774 Adds alternate credentials for alternate projects
  .kokoro/php56.cfg
  .kokoro/php70.cfg
  .kokoro/php71.cfg
  .kokoro/php72.cfg
  .kokoro/secrets.sh.enc
  .kokoro/system_tests.sh
  testing/RUN_ALL_TESTS
  testing/run_test_suite.sh
Labels: fix-it

#777 Update region tags
  appengine/flexible/laravel/app/Exceptions/Handler.php
  appengine/flexible/logging/app.yaml
  appengine/flexible/symfony/src/AppBundle/EventSubscriber/ExceptionSubscriber.php
  error_reporting/quickstart.php
  trace/trace-sample.php
Labels: fix-it

#780 fixes CS and adds cs checker to CI
  .kokoro/docker/Dockerfile.template
  .kokoro/php72.cfg
  .kokoro/system_tests.sh
  appengine/php72/tasks/apps/handler/index.php
  appengine/php72/tasks/apps/handler/test/DeployTest.php
  appengine/php72/tasks/snippets/src/create_task.php
  asset/asset.php
  asset/src/batch_get_assets_history.php
  asset/src/export_assets.php
  asset/test/assetTest.php
  bigtable/api/src/create_cluster.php
  bigtable/api/src/create_family_gc_intersection.php
  bigtable/api/src/create_family_gc_max_age.php
  bigtable/api/src/create_family_gc_max_versions.php
  bigtable/api/src/create_family_gc_nested.php
  bigtable/api/src/create_family_gc_union.php
  bigtable/api/src/create_table.php
  bigtable/api/src/delete_family.php
  bigtable/api/src/delete_instance.php
  bigtable/api/src/list_column_families.php
  bigtable/api/src/list_instance.php
  bigtable/api/src/list_instance_clusters.php
  bigtable/api/src/list_tables.php
  bigtable/api/src/update_gc_rule.php
  bigtable/api/test/bigtableTest.php
  cloud_sql/postgres/pdo/index.php
  cloud_sql/postgres/pdo/src/Votes.php
  cloud_sql/postgres/pdo/template.php
  firestore/src/update_doc_array.php
  language/src/analyze_all.php
  language/src/analyze_all_from_file.php
  language/src/analyze_entities.php
  language/src/analyze_entities_from_file.php
  spanner/src/delete_data_with_dml.php
  spanner/src/update_data_with_dml.php
  spanner/src/write_read_with_dml.php
  spanner/test/spannerTest.php
  storage/src/get_default_event_based_hold.php
  storage/test/RequesterPaysCommandTest.php
  testing/run_all_tests.sh
  video/src/analyze_transcription.php
Labels: Fixit
