Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2020-10, with the labels that each got.

#1184 fix(spanner): skip failing backup test
  spanner/test/spannerBackupTest.php
Labels: api: spanner, cla: yes, samples

#1183 feat(spanner): add standalone samples for NUMERIC type
  spanner/composer.json
  spanner/spanner.php
  spanner/src/add_numeric_column.php
  spanner/src/query_data_with_numeric_parameter.php
  spanner/src/update_data_with_numeric_column.php
  spanner/test/spannerTest.php
Labels: api: spanner, cla: yes, samples

#1175 feat(run): add helloworld
  run/README.md
  run/helloworld/.dockerignore
  run/helloworld/.gcloudignore
  run/helloworld/Dockerfile
  run/helloworld/README.md
  run/helloworld/index.php
  run/helloworld/phpunit.xml.dist
  run/helloworld/test/DeployTest.php
  testing/composer.json
Labels: api: run, cla: yes, samples

#1187 feat(functions/helloworld): add functions_helloworld_get, functions_helloworld_http
  functions/helloworld_get/composer.json
  functions/helloworld_get/index.php
  functions/helloworld_get/phpunit.xml.dist
  functions/helloworld_get/test/DeployTest.php
  functions/helloworld_get/test/SystemTest.php
  functions/helloworld_get/test/UnitTest.php
  functions/helloworld_http/composer.json
  functions/helloworld_http/index.php
  functions/helloworld_http/phpunit.xml.dist
  functions/helloworld_http/test/DeployTest.php
  functions/helloworld_http/test/SystemTest.php
  functions/helloworld_http/test/TestCasesTrait.php
  functions/helloworld_http/test/UnitTest.php
Labels: api: cloudfunctions, cla: yes, samples

#1191 chore(appengine/cloudsql): redirect to newer sample
  appengine/php72/cloudsql/README.md
  appengine/php72/cloudsql/app-postgres.yaml
  appengine/php72/cloudsql/app.yaml
  appengine/php72/cloudsql/composer.json
  appengine/php72/cloudsql/index.php
  appengine/php72/cloudsql/phpunit.xml.dist
  appengine/php72/cloudsql/test/DeployMySQLTest.php
  appengine/php72/cloudsql/test/DeployPostgresTest.php
Labels: api: appengine, cla: yes, samples

#1193 chore: activate snippet-bot
  .github/snippet-bot.yml
Labels: cla: yes, samples

#1200 chore: updates region tag
  video/src/analyze_object_tracking.php
  video/src/analyze_object_tracking_file.php
  video/src/analyze_text_detection.php
  video/src/analyze_text_detection_file.php
Labels: cla: yes

#1203 chore: fix region tag mismatch
  cloud_sql/postgres/pdo/src/app.php
Labels: cla: yes

#1202 chore: add cs check for return-type declaration
  .php_cs.dist
  appengine/php72/getting-started/test/CloudSqlTest.php
  cloud_sql/mysql/pdo/src/Votes.php
  cloud_sql/mysql/pdo/src/app.php
  cloud_sql/mysql/pdo/tests/VotesTest.php
  cloud_sql/postgres/pdo/src/Votes.php
  cloud_sql/postgres/pdo/src/app.php
  cloud_sql/postgres/pdo/tests/VotesTest.php
  cloud_sql/sqlserver/pdo/src/Votes.php
  cloud_sql/sqlserver/pdo/tests/VotesTest.php
  functions/helloworld_get/test/DeployTest.php
  functions/helloworld_get/test/SystemTest.php
  functions/helloworld_get/test/UnitTest.php
  functions/helloworld_http/test/DeployTest.php
  functions/helloworld_http/test/SystemTest.php
  functions/helloworld_http/test/TestCasesTrait.php
  functions/helloworld_http/test/UnitTest.php
Labels: cla: yes

#1196 feat(functions): add functions_http_form_data sample
  functions/helloworld_http/test/SampleUnitTest.php
  functions/http_content_type/test/TestCasesTrait.php
  functions/http_form_data/composer.json
  functions/http_form_data/index.php
  functions/http_form_data/phpunit.xml.dist
  functions/http_form_data/test/DeployTest.php
  functions/http_form_data/test/SystemTest.php
  functions/http_form_data/test/TestCasesTrait.php
  functions/http_form_data/test/fixtures/upload.txt
Labels: api: cloudfunctions, cla: yes, samples

#1205 docs(run): fix run helloworld instructions
  run/README.md
Labels: cla: yes

#1209 chore(functions/form-data): use status code in tests
  functions/http_form_data/test/DeployTest.php
  functions/http_form_data/test/SystemTest.php
  functions/http_form_data/test/TestCasesTrait.php
Labels: api: cloudfunctions, cla: yes, samples

#1208 Add new updated SQL Server sample region tags.
  cloud_sql/sqlserver/pdo/src/Votes.php
  cloud_sql/sqlserver/pdo/src/app.php
Labels: cla: yes, samples

#1198 feat(functions): add functions_log_helloworld
  functions/log_helloworld/composer.json
  functions/log_helloworld/index.php
  functions/log_helloworld/phpunit.xml.dist
  functions/log_helloworld/test/DeployTest.php
  functions/log_helloworld/test/SystemTest.php
  functions/log_helloworld/test/TestCasesTrait.php
  functions/log_helloworld/test/UnitTest.php
Labels: api: cloudfunctions, cla: yes, samples
