Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2020-11, with the labels that each got.

#1210 chore(functions): clean up existing helloworld samples
  functions/helloworld_get/test/DeployTest.php
  functions/helloworld_get/test/SystemTest.php
  functions/helloworld_get/test/TestCasesTrait.php
  functions/helloworld_get/test/UnitTest.php
  functions/helloworld_http/test/DeployTest.php
  functions/helloworld_http/test/SystemTest.php
  functions/helloworld_http/test/TestCasesTrait.php
  functions/helloworld_http/test/UnitTest.php
Labels: api: cloudfunctions, cla: yes, do not merge, samples

#1211 Remove outdated SQL Server sample region tags.
  cloud_sql/sqlserver/pdo/src/Votes.php
  cloud_sql/sqlserver/pdo/src/app.php
Labels: cla: yes

#1216 docs(run): update region tag
  run/helloworld/Dockerfile
  run/helloworld/index.php
Labels: api: run, cla: yes

#1215 chore(functions): Revise test coverage for CI utility updates
  functions/concepts_filesystem/test/DeployTest.php
  functions/concepts_filesystem/test/SystemTest.php
  functions/concepts_filesystem/test/UnitTest.php
  functions/concepts_requests/test/DeployTest.php
  functions/concepts_requests/test/SystemTest.php
  functions/concepts_requests/test/UnitTest.php
  functions/env_vars/test/DeployTest.php
  functions/env_vars/test/SystemTest.php
  functions/env_vars/test/TestCasesTrait.php
  functions/env_vars/test/UnitTest.php
  functions/helloworld_get/test/DeployTest.php
  functions/helloworld_get/test/SystemTest.php
  functions/helloworld_get/test/UnitTest.php
  functions/helloworld_http/test/DeployTest.php
  functions/helloworld_http/test/SystemTest.php
  functions/helloworld_http/test/UnitTest.php
  functions/http_content_type/test/DeployTest.php
  functions/http_content_type/test/SystemTest.php
  functions/http_content_type/test/UnitTest.php
  functions/http_cors/test/DeployTest.php
  functions/http_cors/test/SystemTest.php
  functions/http_cors/test/UnitTest.php
  functions/http_form_data/test/DeployTest.php
  functions/http_form_data/test/SystemTest.php
  functions/http_method/test/DeployTest.php
  functions/http_method/test/SystemTest.php
  functions/http_method/test/UnitTest.php
  functions/log_helloworld/test/DeployTest.php
  functions/log_helloworld/test/SystemTest.php
  functions/log_helloworld/test/UnitTest.php
Labels: api: cloudfunctions, cla: yes

#1218 chore(functions/log_helloworld): mention var_dump
  functions/log_helloworld/index.php
Labels: api: cloudfunctions, cla: yes

#1212 feat(functions): add Slack samples
  functions/slack_slash_command/composer.json
  functions/slack_slash_command/index.php
  functions/slack_slash_command/phpunit.xml.dist
  functions/slack_slash_command/test/DeployTest.php
  functions/slack_slash_command/test/IntegrationTest.php
  functions/slack_slash_command/test/TestCasesTrait.php
Labels: api: cloudfunctions, cla: yes, samples

#1199 feat(functions): add scopes sample
  functions/tips_scopes/composer.json
  functions/tips_scopes/index.php
  functions/tips_scopes/phpunit.xml.dist
  functions/tips_scopes/test/DeployTest.php
  functions/tips_scopes/test/IntegrationTest.php
  functions/tips_scopes/test/UnitTest.php
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1220 chore(functions/log): add more logging methods
  functions/log_helloworld/index.php
Labels: api: cloudfunctions, cla: yes

#1223 refactor(functions): Directory name log_helloworld -> helloworld_log
  functions/helloworld_log/composer.json
  functions/helloworld_log/index.php
  functions/helloworld_log/phpunit.xml.dist
  functions/helloworld_log/test/DeployTest.php
  functions/helloworld_log/test/SystemTest.php
  functions/helloworld_log/test/TestCasesTrait.php
  functions/helloworld_log/test/UnitTest.php
Labels: api: cloudfunctions, cla: yes

#1222 fixes for storage and bigquery nightly tests
  bigquery/api/src/import_from_storage_csv.php
  bigquery/api/src/import_from_storage_csv_autodetect.php
  bigquery/api/src/import_from_storage_json.php
  bigquery/api/src/import_from_storage_json_autodetect.php
  bigquery/api/src/import_from_storage_orc.php
  bigquery/api/src/import_from_storage_parquet.php
  bigquery/api/test/bigqueryTest.php
  storage/test/storageTest.php
Labels: cla: yes

#1221 chore(firestore): fix risky tests
  firestore/src/collection_ref.php
  firestore/src/document_path_ref.php
  firestore/src/document_ref.php
  firestore/src/invalid_range_order_by_query.php
  firestore/src/invalid_range_query.php
  firestore/src/subcollection_ref.php
  firestore/test/firestoreTest.php
Labels: api: firestore, cla: yes

#1206 feat: init eventarc generic sample
  eventarc/generic/.dockerignore
  eventarc/generic/.gcloudignore
  eventarc/generic/Dockerfile
  eventarc/generic/README.md
  eventarc/generic/index.php
  eventarc/generic/phpunit.xml.dist
  eventarc/generic/test/DeployTest.php
Labels: cla: yes, samples
