Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2020-03, with the labels that each got.

#1033 Updates symfony and tests for symfony-demo 1.5
  appengine/php72/symfony-framework/src/EventSubscriber/ExceptionSubscriber.php
  appengine/php72/symfony-framework/test/DeployDoctrineTest.php
  appengine/php72/symfony-framework/test/DeploySymfonyTrait.php
  appengine/php72/symfony-framework/test/DeployTest.php
Labels: cla: yes

#1035 updates all storage sample region tags
  storage/src/add_bucket_acl.php
  storage/src/add_bucket_conditional_iam_binding.php
  storage/src/add_bucket_default_acl.php
  storage/src/add_bucket_iam_member.php
  storage/src/add_bucket_label.php
  storage/src/add_object_acl.php
  storage/src/copy_object.php
  storage/src/create_bucket.php
  storage/src/delete_bucket.php
  storage/src/delete_bucket_acl.php
  storage/src/delete_bucket_default_acl.php
  storage/src/delete_object.php
  storage/src/delete_object_acl.php
  storage/src/disable_requester_pays.php
  storage/src/download_encrypted_object.php
  storage/src/download_file_requester_pays.php
  storage/src/download_object.php
  storage/src/enable_requester_pays.php
  storage/src/generate_encryption_key.php
  storage/src/get_bucket_acl.php
  storage/src/get_bucket_labels.php
  storage/src/get_object_acl.php
  storage/src/get_requester_pays_status.php
  storage/src/list_buckets.php
  storage/src/list_objects.php
  storage/src/list_objects_with_prefix.php
  storage/src/make_public.php
  storage/src/move_object.php
  storage/src/object_metadata.php
  storage/src/remove_bucket_iam_member.php
  storage/src/remove_bucket_label.php
  storage/src/rotate_encryption_key.php
  storage/src/upload_encrypted_object.php
  storage/src/upload_object.php
  storage/src/view_bucket_iam_members.php
Labels: cla: yes

#1036 feat: add firestore reference data type
  firestore/src/add_doc_data_types.php
Labels: cla: yes

#1038 test: add retries to vision tests
  vision/test/visionTest.php
Labels: cla: yes

#1034 docs: Remove symfony README in favor of published tutorial
  appengine/php72/symfony-framework/README.md
Labels: automerge, cla: yes

#1041 feat: add query optimizer version samples
  spanner/composer.json
  spanner/spanner.php
  spanner/src/create_client_with_query_options.php
  spanner/src/query_data_with_query_options.php
  spanner/test/spannerTest.php
Labels: api: spanner, cla: yes

#1045 feat: add remove conditional iam binding
  storage/composer.json
  storage/src/remove_bucket_conditional_iam_binding.php
  storage/storage.php
  storage/test/IamCommandTest.php
Labels: automerge, cla: yes
