Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2020-12, with the labels that each got.

#1237 fix: ensure speech tests are case sensitive
  speech/test/speechTest.php
Labels: cla: yes, samples

#1230 feat: add dead letter queue samples
  pubsub/api/composer.json
  pubsub/api/pubsub.php
  pubsub/api/src/dead_letter_create_subscription.php
  pubsub/api/src/dead_letter_delivery_attempt.php
  pubsub/api/src/dead_letter_remove.php
  pubsub/api/src/dead_letter_update_subscription.php
  pubsub/api/test/DeadLetterPolicyTest.php
  pubsub/api/test/pubsubTest.php
Labels: api: pubsub, cla: yes, samples

#1236 feat: added a profanity filter sample
  speech/src/profanity_filter.php
  speech/src/profanity_filter_gcs.php
  speech/test/speechTest.php
Labels: cla: yes, samples

#1238 refactor: updated the quickstart to use gcs
  speech/quickstart.php
Labels: cla: yes, samples

#1225 feat(functions): add Firestore sample
  functions/firebase_firestore/composer.json
  functions/firebase_firestore/index.php
  functions/firebase_firestore/phpunit.xml.dist
  functions/firebase_firestore/test/DeployTest.php
  functions/firebase_firestore/test/IntegrationTest.php
Labels: api: cloudfunctions, cla: yes, samples
