Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2020-08, with the labels that each got.

#1150 feat: add subscription detach sample
  pubsub/api/composer.json
  pubsub/api/pubsub.php
  pubsub/api/src/detach_subscription.php
  pubsub/api/test/pubsubTest.php
Labels: cla: yes

#1154 fix: update dlp to 0.27
  dlp/composer.json
  dlp/quickstart.php
  dlp/src/create_inspect_template.php
  dlp/src/create_trigger.php
  dlp/src/deidentify_dates.php
  dlp/src/deidentify_fpe.php
  dlp/src/deidentify_mask.php
  dlp/src/inspect_image_file.php
  dlp/src/inspect_string.php
  dlp/src/inspect_text_file.php
  dlp/src/redact_image.php
Labels: cla: yes

#1155 fix: flex and task tests
  tasks/test/tasksTest.php
  testing/composer.json
Labels: cla: yes

#1156 fix: Flex Logging and IOT tests
  appengine/flexible/logging/app.php
  iot/composer.json
  iot/test/iotTest.php
Labels: cla: yes

#1157 tests: drop PHP 7.1 and add PHP 7.2
  .kokoro/docker/php74/Dockerfile
  .kokoro/php73.cfg
  .kokoro/php74.cfg
  appengine/flexible/helloworld/composer.json
Labels: cla: yes, kokoro:run-all

#1087 updates for slim v4
  appengine/php72/getting-started/composer.json
  appengine/php72/getting-started/src/app.php
  appengine/php72/getting-started/src/controllers.php
  appengine/php72/getting-started/test/CloudSqlTest.php
  appengine/php72/getting-started/test/ControllersTest.php
  appengine/php72/slim-framework/composer.json
Labels: >= PHP 7.2, cla: yes

#1158 test: misc php 7.4 fixes
  .kokoro/docker/php74/Dockerfile
  testing/composer.json
Labels: cla: yes

#1159 fix: remove/upgrade test deps already defined in testing/composer.json
  appengine/flexible/analytics/composer.json
  appengine/flexible/datastore/composer.json
  appengine/flexible/logging/composer.json
  appengine/flexible/storage/composer.json
  testing/composer.json
Labels: cla: yes

#1161 fix: add debugging for flex logging test
  appengine/flexible/logging/test/LocalTest.php
Labels: cla: yes

#1160 fix(cloud-sql): fix region tag
  cloud_sql/sqlserver/pdo/src/app.php
Labels: cla: yes

#1164 test: add flex logging as a flakey tests
  testing/run_test_suite.sh
Labels: cla: yes
