Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2020-04, with the labels that each got.

#1046 feat: spanner backup and restore code samples
  spanner/composer.json
  spanner/spanner.php
  spanner/src/cancel_backup.php
  spanner/src/create_backup.php
  spanner/src/delete_backup.php
  spanner/src/list_backup_operations.php
  spanner/src/list_backups.php
  spanner/src/list_database_operations.php
  spanner/src/restore_backup.php
  spanner/src/update_backup.php
  spanner/test/spannerTest.php
Labels: cla: yes

#1052 test: Fix Spanner Backup tests
  spanner/test/spannerBackupTest.php
  spanner/test/spannerTest.php
  testing/run_test_suite.sh
Labels: cla: yes

#1051 feat: Adds PHP code samples for SecurityCenter
  .kokoro/secrets-example.sh
  .kokoro/secrets.sh.enc
  securitycenter/composer.json
  securitycenter/phpunit.xml.dist
  securitycenter/src/create_notification.php
  securitycenter/src/delete_notification.php
  securitycenter/src/get_notification.php
  securitycenter/src/list_notification.php
  securitycenter/src/receive_notification.php
  securitycenter/src/update_notification.php
  securitycenter/test/SecurityCenterTest.php
Labels: cla: yes

#1043 SecretManager bump version v1beta1->v1
  secretmanager/composer.json
  secretmanager/quickstart.php
  secretmanager/src/access_secret_version.php
  secretmanager/src/add_secret_version.php
  secretmanager/src/create_secret.php
  secretmanager/src/delete_secret.php
  secretmanager/src/destroy_secret_version.php
  secretmanager/src/disable_secret_version.php
  secretmanager/src/enable_secret_version.php
  secretmanager/src/get_secret.php
  secretmanager/src/get_secret_version.php
  secretmanager/src/iam_grant_access.php
  secretmanager/src/iam_revoke_access.php
  secretmanager/src/list_secret_versions.php
  secretmanager/src/list_secrets.php
  secretmanager/src/update_secret.php
  secretmanager/test/quickstartTest.php
  secretmanager/test/secretmanagerTest.php
Labels: cla: yes

#1054 fix: video region tags
  video/src/analyze_labels_file.php
  video/src/analyze_labels_gcs.php
  video/test/videoTest.php
Labels: cla: yes

#1049 storage: add v4 post policy
  storage/composer.json
  storage/src/generate_v4_post_policy.php
  storage/storage.php
  storage/test/GenerateV4PostPolicy.php
  storage/test/ObjectSignedUrlTest.php
Labels: cla: yes

#1055 chore: updates all dependencies and updates dependency script
  appengine/flexible/logging/composer.json
  appengine/php55/grpc/composer.json
  appengine/php72/errorreporting/composer.json
  appengine/php72/grpc/composer.json
  asset/composer.json
  bigquerydatatransfer/composer.json
  bigtable/composer.json
  debugger/composer.json
  dlp/composer.json
  endpoints/getting-started/composer.json
  error_reporting/composer.json
  error_reporting/test/VerifyReportedErrorTrait.php
  firestore/composer.json
  iap/composer.json
  iot/composer.json
  iot/src/list_gateways.php
  language/composer.json
  logging/composer.json
  monitoring/composer.json
  pubsub/app/composer.json
  secretmanager/composer.json
  securitycenter/composer.json
  spanner/composer.json
  spanner/test/spannerBackupTest.php
  speech/composer.json
  storage/composer.json
  testing/run_dependency_update.sh
  texttospeech/composer.json
  trace/composer.json
  translate/composer.json
  vision/composer.json
Labels: cla: yes

#1061 chore(deps): moves renovate.json and adds preset preserveSemverRanges
  .github/renovate.json
  renovate.json
Labels: cla: yes

#1063 fixes cloud trace and updates renovate
  .github/renovate.json
  trace/composer.json
Labels: cla: yes

#1081 Fix test script
  .kokoro/docker/php73/Dockerfile
  debugger/composer.json
  testing/run_test_suite.sh
Labels: cla: yes

#1082 fix: fixes storage samples
  renovate.json
  storage/src/remove_bucket_conditional_iam_binding.php
  storage/src/remove_bucket_iam_member.php
  storage/storage.php
  storage/test/IamCommandTest.php
  storage/test/ObjectAclCommandTest.php
  storage/test/ObjectsCommandTest.php
  storage/test/quickstartTest.php
  storage/test/storageTest.php
  testing/run_test_suite.sh
Labels: cla: yes

#1084 Small typo in simple PHP example
  translate/src/translate.php
Labels: cla: yes

#1086 fixed typo
  translate/src/translate_with_model.php
Labels: cla: yes

#1091 test: fix CS fixer by adding it directly to docker
  .kokoro/docker/php73/Dockerfile
  .kokoro/system_tests.sh
Labels: cla: yes

#1088 fix(spanner): display LRO progress
  spanner/composer.json
  spanner/src/list_backup_operations.php
  spanner/src/list_database_operations.php
  spanner/test/spannerBackupTest.php
Labels: automerge, cla: yes

#1093 fix: use DELETE FROM for consistency
  spanner/src/delete_data_with_dml.php
  spanner/src/delete_data_with_partitioned_dml.php
Labels: api: spanner, automerge, cla: yes

#1096 Fix vision_classification_predict.php
  automl/src/vision_classification_predict.php
Labels: cla: yes

#1098 fix(vision): add fix for changing vision model test
  appengine/flexible/helloworld/composer.json
  vision/test/visionTest.php
Labels: cla: yes
