Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2021-11, with the labels that each got.

#1447 docs: consolidated client creation snippets
  firestore/src/setup_client_create.php
  firestore/src/setup_client_create_with_project_id.php
  firestore/test/firestoreTest.php
Labels: cla: yes, samples

#1552 Rename CLOUD_SQL_CONNECTION_NAME to INSTANCE_CONNECTION_NAME
  cloud_sql/mysql/pdo/README.md
  cloud_sql/mysql/pdo/app.flex.yaml
  cloud_sql/mysql/pdo/app.standard.yaml
  cloud_sql/mysql/pdo/src/DBInitializer.php
  cloud_sql/postgres/pdo/README.md
  cloud_sql/postgres/pdo/app.flex.yaml
  cloud_sql/postgres/pdo/app.standard.yaml
  cloud_sql/postgres/pdo/src/DBInitializer.php
  cloud_sql/sqlserver/pdo/README.md
  cloud_sql/sqlserver/pdo/src/DBInitializer.php
Labels: cla: yes, samples

#1548 Add a quickstart sample for storage transfer service
  storagetransfer/composer.json
  storagetransfer/phpunit.xml.dist
  storagetransfer/src/quickstart.php
  storagetransfer/test/StorageTransferTest.php
Labels: cla: yes, samples

#1463 samples(spanner): add JSON samples
  spanner/src/add_json_column.php
  spanner/src/query_data_with_json_parameter.php
  spanner/src/update_data_with_json_column.php
  spanner/test/spannerTest.php
Labels: cla: yes, api: spanner, samples

#1558 fix: php version check for tests
  testing/run_test_suite.sh
Labels: cla: yes, samples

#1553 refactor(functions): declarative function signature for helloworld_http
  functions/helloworld_http/SampleUnitTest.php
  functions/helloworld_http/composer.json
  functions/helloworld_http/index.php
  functions/helloworld_pubsub/composer.json
Labels: cla: yes, api: cloudfunctions, samples

#1554 refactor(functions): declarative function signature for helloworld_pubsub
  functions/helloworld_pubsub/SampleUnitTest.php
  functions/helloworld_pubsub/index.php
Labels: cla: yes, api: cloudfunctions, samples

#1557 bug(bigtable): fixed getting the error message from LRO
  bigtable/src/create_cluster.php
Labels: cla: yes, type: bug, api: bigtable, samples

#1563 fix: php version check
  functions/helloworld_pubsub/composer.json
  testing/check_version.php
  testing/composer.json
  testing/run_test_suite.sh
Labels: cla: yes, samples

#1372 feat(appengine): add custom extension sample
  appengine/standard/extensions/.gcloudignore
  appengine/standard/extensions/.gitignore
  appengine/standard/extensions/app.yaml
  appengine/standard/extensions/composer.json
  appengine/standard/extensions/ext/config.m4
  appengine/standard/extensions/ext/my_custom_extension.c
  appengine/standard/extensions/ext/my_custom_extension.h
  appengine/standard/extensions/index.php
  appengine/standard/extensions/php.ini
  appengine/standard/extensions/test/DeployTest.php
Labels: cla: yes, api: appengine, samples

#1495 Multiple Updates
  appengine/flexible/drupal8/README.md
  appengine/standard/errorreporting/README.md
  appengine/standard/grpc/README.md
  appengine/standard/logging/README.md
  appengine/standard/memorystore/README.md
  appengine/standard/tasks/apps/handler/README.md
  appengine/standard/trace/README.md
  cloud_sql/mysql/pdo/README.md
  cloud_sql/postgres/pdo/README.md
  error_reporting/README.md
  spanner/README.md
  vision/README.md
Labels: cla: yes, samples
