Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2021-02, with the labels that each got.

#1258 feat(functions): add retriable events sample
  functions/tips_retry/composer.json
  functions/tips_retry/index.php
  functions/tips_retry/phpunit.xml.dist
  functions/tips_retry/test/DeployTest.php
  functions/tips_retry/test/IntegrationTest.php
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1260 feat(functions): add infinite retries sample
  functions/tips_infinite_retries/composer.json
  functions/tips_infinite_retries/index.php
  functions/tips_infinite_retries/phpunit.xml.dist
  functions/tips_infinite_retries/test/DeployTest.php
  functions/tips_infinite_retries/test/IntegrationTest.php
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1239 docs: Wrap samples with future prefix
  securitycenter/src/create_notification.php
  securitycenter/src/delete_notification.php
  securitycenter/src/get_notification.php
  securitycenter/src/list_notification.php
  securitycenter/src/receive_notification.php
  securitycenter/src/update_notification.php
Labels: automerge, cla: yes, samples

#1245 feat(functions): add ImageMagick samples
  .kokoro/secrets-example.sh
  .kokoro/secrets.sh.enc
  functions/imagemagick/.gcloudignore
  functions/imagemagick/README.md
  functions/imagemagick/composer.json
  functions/imagemagick/index.php
  functions/imagemagick/php.ini
  functions/imagemagick/phpunit.xml.dist
  functions/imagemagick/test/DeployTest.php
  functions/imagemagick/test/IntegrationTest.php
  functions/imagemagick/test/TestCasesTrait.php
Labels: api: cloudfunctions, cla: yes, samples

#1276 fix: remove unused psr/cache from bigtable
  bigtable/composer.json
Labels: cla: yes, samples

#1275 chore(testing): add ability to skip GAE Flex tests
  appengine/flexible/analytics/phpunit.xml.dist
  appengine/flexible/datastore/phpunit.xml.dist
  appengine/flexible/drupal8/phpunit.xml.dist
  appengine/flexible/helloworld/phpunit.xml.dist
  appengine/flexible/laravel/phpunit.xml.dist
  appengine/flexible/logging/phpunit.xml.dist
  appengine/flexible/memcache/phpunit.xml.dist
  appengine/flexible/metadata/phpunit.xml.dist
  appengine/flexible/staticcontent/phpunit.xml.dist
  appengine/flexible/storage/phpunit.xml.dist
  appengine/flexible/symfony/phpunit.xml.dist
  appengine/flexible/tasks/phpunit.xml.dist
  appengine/flexible/twilio/phpunit.xml.dist
  appengine/flexible/websockets/phpunit.xml.dist
  appengine/flexible/wordpress/phpunit.xml.dist
  endpoints/getting-started/phpunit.xml.dist
Labels: automerge, cla: yes, samples

#1281 chore(testing): disable supervisord GAE deployment tests
  appengine/flexible/supervisord/addition/phpunit.xml.dist
  appengine/flexible/supervisord/replacement/phpunit.xml.dist
Labels: cla: yes, samples

#1283 chore(appengine): fix failing deployment tests
  appengine/standard/slim-framework/.gcloudignore
  appengine/standard/slim-framework/composer.json
  appengine/standard/slim-framework/index.php
Labels: api: appengine, automerge, cla: yes, samples

#1286 feat(spanner): add sample for commit stats
  spanner/src/get_commit_stats.php
  spanner/test/spannerTest.php
Labels: api: spanner, cla: yes, samples

#1291 chore: descriptive comment for path variable
  texttospeech/src/synthesize_text_file.php
Labels: cla: yes, samples

#1290 feat(spanner): add samples for PITR
  spanner/src/create_backup.php
  spanner/src/create_database_with_version_retention_period.php
  spanner/src/restore_backup.php
  spanner/test/spannerBackupTest.php
Labels: api: spanner, cla: yes, samples
