Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2021-01, with the labels that each got.

#1246 feat: adds a new multi region sample
  speech/src/multi_region_gcs.php
  speech/src/profanity_filter.php
  speech/src/profanity_filter_gcs.php
  speech/test/speechTest.php
Labels: cla: yes, samples

#1252 feat(functions): add phpinfo sample
  functions/tips_phpinfo/composer.json
  functions/tips_phpinfo/index.php
  functions/tips_phpinfo/phpunit.xml.dist
  functions/tips_phpinfo/test/DeployTest.php
  functions/tips_phpinfo/test/IntegrationTest.php
Labels: api: cloudfunctions, cla: yes, samples

#1254 test: unskip testListBackupOperations
  spanner/test/spannerBackupTest.php
Labels: cla: yes, samples

#1241 feature(functions): add Firebase remote config sample
  functions/firebase_remote_config/composer.json
  functions/firebase_remote_config/index.php
  functions/firebase_remote_config/phpunit.xml.dist
  functions/firebase_remote_config/test/DeployTest.php
  functions/firebase_remote_config/test/IntegrationTest.php
Labels: api: cloudfunctions, cla: yes, samples

#1247 docs: standardize region tagging
  asset/src/search_all_iam_policies.php
  asset/src/search_all_resources.php
Labels: cla: yes, samples

#1263 chore(GAE flex): rm unused SQL samples
  appengine/flexible/cloudsql-mysql/README.md
  appengine/flexible/cloudsql-mysql/app.php
  appengine/flexible/cloudsql-mysql/app.yaml
  appengine/flexible/cloudsql-mysql/composer.json
  appengine/flexible/cloudsql-mysql/index.php
  appengine/flexible/cloudsql-mysql/phpunit.xml.dist
  appengine/flexible/cloudsql-mysql/test/DeployTest.php
  appengine/flexible/cloudsql-mysql/test/LocalTest.php
  appengine/flexible/cloudsql-postgres/README.md
  appengine/flexible/cloudsql-postgres/app.php
  appengine/flexible/cloudsql-postgres/app.yaml
  appengine/flexible/cloudsql-postgres/composer.json
  appengine/flexible/cloudsql-postgres/index.php
  appengine/flexible/cloudsql-postgres/phpunit.xml.dist
  appengine/flexible/cloudsql-postgres/test/DeployTest.php
  appengine/flexible/cloudsql-postgres/test/LocalTest.php
Labels: cla: yes, samples

#1261 chore(GAE flex): rm 3rd-party email samples
  appengine/flexible/mailgun/README.md
  appengine/flexible/mailgun/app.php
  appengine/flexible/mailgun/app.yaml
  appengine/flexible/mailgun/attachment.txt
  appengine/flexible/mailgun/composer.json
  appengine/flexible/mailgun/index.php
  appengine/flexible/mailgun/phpunit.xml.dist
  appengine/flexible/mailgun/test/DeployTest.php
  appengine/flexible/mailjet/README.md
  appengine/flexible/mailjet/app.php
  appengine/flexible/mailjet/app.yaml
  appengine/flexible/mailjet/composer.json
  appengine/flexible/mailjet/index.php
  appengine/flexible/mailjet/phpunit.xml.dist
  appengine/flexible/mailjet/test/DeployTest.php
  appengine/flexible/sendgrid/README.md
  appengine/flexible/sendgrid/app.php
  appengine/flexible/sendgrid/app.yaml
  appengine/flexible/sendgrid/composer.json
  appengine/flexible/sendgrid/index.php
  appengine/flexible/sendgrid/phpunit.xml.dist
  appengine/flexible/sendgrid/test/DeployTest.php
  appengine/flexible/sendgrid/test/LocalTest.php
Labels: cla: yes, samples

#1264 Add iot team as code sample owners
  CODEOWNERS
Labels: cla: yes, samples

#1262 feat(functions): add helloworld pubsub sample
  functions/helloworld_pubsub/composer.json
  functions/helloworld_pubsub/index.php
  functions/helloworld_pubsub/phpunit.xml.dist
  functions/helloworld_pubsub/test/DeployTest.php
  functions/helloworld_pubsub/test/IntegrationTest.php
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1256 docs: standardize region tagging pt.2
  asset/src/search_all_iam_policies.php
  asset/src/search_all_resources.php
Labels: automerge, cla: yes, samples

#1251 Added integration tests for Cloud SQL
  .kokoro/secrets.sh.enc
  cloud_sql/mysql/pdo/composer.json
  cloud_sql/mysql/pdo/phpunit.xml.dist
  cloud_sql/mysql/pdo/src/DBInitializer.php
  cloud_sql/mysql/pdo/src/Votes.php
  cloud_sql/mysql/pdo/src/app.php
  cloud_sql/mysql/pdo/tests/IntegrationTest.php
  cloud_sql/mysql/pdo/views/template.twig
  cloud_sql/postgres/pdo/composer.json
  cloud_sql/postgres/pdo/src/DBInitializer.php
  cloud_sql/postgres/pdo/src/Votes.php
  cloud_sql/postgres/pdo/src/app.php
  cloud_sql/postgres/pdo/tests/IntegrationTest.php
  cloud_sql/postgres/pdo/views/template.twig
  cloud_sql/sqlserver/pdo/composer.json
  cloud_sql/sqlserver/pdo/phpunit.xml.dist
  cloud_sql/sqlserver/pdo/src/DBInitializer.php
  cloud_sql/sqlserver/pdo/src/Votes.php
  cloud_sql/sqlserver/pdo/src/app.php
  cloud_sql/sqlserver/pdo/tests/IntegrationTest.php
  cloud_sql/sqlserver/pdo/views/template.twig
Labels: automerge, cla: yes, samples

#1265 chore: move dockerfiles to googleapis/testing-infra-docker
  .kokoro/docker/.gitignore
  .kokoro/docker/Dockerfile.template
  .kokoro/docker/Makefile
  .kokoro/docker/php55/Dockerfile
  .kokoro/docker/php73/Dockerfile
  .kokoro/docker/php74/Dockerfile
Labels: automerge, cla: yes, samples

#1268 fix: corrected region tag typo
  cloud_sql/sqlserver/pdo/src/DBInitializer.php
Labels: automerge, cla: yes, samples
