Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2021-09, with the labels that each got.

#1501 chore: configure functions to update in one pr
  renovate.json
Labels: cla: yes, samples

#1500 feat: Added reCAPTCHA samples for site key operations
  recaptcha/README.md
  recaptcha/composer.json
  recaptcha/phpunit.xml.dist
  recaptcha/src/create_key.php
  recaptcha/src/delete_key.php
  recaptcha/src/get_key.php
  recaptcha/src/list_keys.php
  recaptcha/src/update_key.php
  recaptcha/test/recaptchaTest.php
Labels: cla: yes, samples

#1479 feat: CloudAsset: Add sample code for ListAssets
  asset/src/list_assets.php
  asset/test/assetTest.php
Labels: cla: yes, api: cloudasset, samples

#1506 Refactoring compute_instances_operation_check sample
  compute/cloud-client/instances/composer.json
  compute/cloud-client/instances/src/create_instance.php
  compute/cloud-client/instances/src/delete_instance.php
  compute/cloud-client/instances/src/wait_for_operation.php
Labels: cla: yes, api: compute, samples
