Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2021-05, with the labels that each got.

#1358 add LRO to compute samples
  compute/cloud-client/instances/src/create_instance.php
  compute/cloud-client/instances/src/delete_instance.php
Labels: cla: yes, samples

#1336 feat: add deployment tests, remove unused scripts + GAE storage samples
  .kokoro/deploy_gae.cfg
  .kokoro/deploy_gcf.cfg
  .kokoro/deploy_misc.cfg
  .kokoro/secrets.sh.enc
  appengine/standard/errorreporting/test/DeployTest.php
  appengine/standard/getting-started/composer.json
  appengine/standard/laravel-framework/app-dbsessions.yaml
  appengine/standard/laravel-framework/bootstrap/app.php
  appengine/standard/laravel-framework/phpunit.xml.dist
  appengine/standard/laravel-framework/test/DeployDatabaseTest.php
  appengine/standard/laravel-framework/test/DeployStackdriverTest.php
  appengine/standard/laravel-framework/test/DeployTest.php
  appengine/standard/logging/test/DeployTest.php
  appengine/standard/slim-framework/index.php
  appengine/standard/storage/README.md
  appengine/standard/storage/app.yaml
  appengine/standard/storage/composer.json
  appengine/standard/storage/index.php
  appengine/standard/storage/phpunit.xml.dist
  appengine/standard/storage/src/read_metadata.php
  appengine/standard/storage/src/register_stream_wrapper.php
  appengine/standard/storage/src/upload_file.php
  appengine/standard/storage/src/write_default.php
  appengine/standard/storage/src/write_default_stream.php
  appengine/standard/storage/src/write_file.php
  appengine/standard/storage/src/write_metadata.php
  appengine/standard/storage/src/write_options.php
  appengine/standard/storage/src/write_public.php
  appengine/standard/storage/src/write_stream.php
  appengine/standard/storage/src/write_with_caching.php
  appengine/standard/storage/test/DeployTest.php
  appengine/standard/symfony-framework/phpunit.xml.dist
  appengine/standard/symfony-framework/test/DeploySymfonyTrait.php
  appengine/standard/wordpress/composer.json
  appengine/standard/wordpress/phpunit.xml.dist
  appengine/standard/wordpress/test/DeployTest.php
  eventarc/generic/test/DeployTest.php
  functions/firebase_firestore/test/DeployTest.php
  functions/firebase_firestore_reactive/test/DeployTest.php
  functions/firebase_remote_config/test/DeployTest.php
  functions/firebase_rtdb/test/DeployTest.php
  functions/firebase_rtdb/test/IntegrationTest.php
  functions/helloworld_pubsub/test/DeployTest.php
  functions/helloworld_storage/test/DeployTest.php
  functions/http_cors/test/DeployTest.php
  functions/imagemagick/index.php
  functions/imagemagick/test/DeployTest.php
  functions/slack_slash_command/test/TestCasesTrait.php
  functions/tips_infinite_retries/index.php
  functions/tips_infinite_retries/test/DeployTest.php
  functions/tips_infinite_retries/test/IntegrationTest.php
  functions/tips_retry/test/DeployTest.php
  run/helloworld/test/DeployTest.php
  testing/run_dependency_check.sh
  testing/run_dependency_update.sh
  testing/run_test_suite.sh
Labels: cla: yes, kokoro:run-all, samples

#1356 chore: update pubsub samples to new test runner
  pubsub/api/README.md
  pubsub/api/composer.json
  pubsub/api/pubsub.php
  pubsub/api/src/create_push_subscription.php
  pubsub/api/src/create_subscription.php
  pubsub/api/src/create_topic.php
  pubsub/api/src/dead_letter_create_subscription.php
  pubsub/api/src/dead_letter_delivery_attempt.php
  pubsub/api/src/dead_letter_remove.php
  pubsub/api/src/dead_letter_update_subscription.php
  pubsub/api/src/delete_subscription.php
  pubsub/api/src/delete_topic.php
  pubsub/api/src/detach_subscription.php
  pubsub/api/src/get_subscription_policy.php
  pubsub/api/src/get_topic_policy.php
  pubsub/api/src/list_subscriptions.php
  pubsub/api/src/list_topics.php
  pubsub/api/src/publish_message.php
  pubsub/api/src/publish_message_batch.php
  pubsub/api/src/pull_messages.php
  pubsub/api/src/set_subscription_policy.php
  pubsub/api/src/set_topic_policy.php
  pubsub/api/src/test_subscription_permissions.php
  pubsub/api/src/test_topic_permissions.php
  pubsub/api/test/DeadLetterPolicyTest.php
  pubsub/api/test/pubsubTest.php
Labels: cla: yes, samples

#1353 chore: cloud-compute samples preparation to incorporate them into cloud.google.com documentation
  compute/cloud-client/instances/composer.json
  compute/cloud-client/instances/src/create_instance.php
  compute/cloud-client/instances/src/delete_instance.php
  compute/cloud-client/instances/src/list_instances.php
Labels: api: compute, cla: yes, samples

#1361 fix(compute): lro samples
  compute/cloud-client/instances/src/create_instance.php
  compute/cloud-client/instances/src/delete_instance.php
Labels: api: compute, automerge, cla: yes, samples, type: bug

#1362 Fix typo in readme
  cloud_sql/postgres/pdo/README.md
Labels: cla: yes, samples

#1366 fix: set a default firebase project if an alt project isnt used
  .kokoro/secrets.sh.enc
Labels: automerge, cla: yes, samples

#1365 chore(Cloud SQL): upgrade PHP version from 7.2 to 7.4
  cloud_sql/mysql/pdo/app.standard.yaml
  cloud_sql/postgres/pdo/app.standard.yaml
Labels: api: cloudsql, cla: yes, samples

#1367 chore: update compute to v0.3.0
  compute/cloud-client/helloworld/app.php
  compute/cloud-client/helloworld/composer.json
  compute/cloud-client/instances/composer.json
  compute/cloud-client/instances/src/list_instances.php
Labels: cla: yes, samples

#1368 Update CODEOWNERS / Blunderbuss for SoDA teams
  .github/.blunderbuss.yml
  CODEOWNERS
Labels: cla: yes, samples
