Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2021-06, with the labels that each got.

#1354 feat: new sample - list all compute instances
  compute/cloud-client/instances/src/list_all_instances.php
  compute/cloud-client/instances/test/instancesTest.php
Labels: api: compute, automerge, cla: yes, samples

#1382 chore: remove unused dep
  datastore/api/composer.json
  datastore/quickstart/composer.json
  datastore/tutorial/composer.json
  pubsub/api/composer.json
  pubsub/quickstart/composer.json
Labels: cla: yes, samples

#1379 chore: upgrade IOT samples to new format
  iot/README.md
  iot/composer.json
  iot/iot.php
  iot/src/bind_device_to_gateway.php
  iot/src/create_es_device.php
  iot/src/create_gateway.php
  iot/src/create_registry.php
  iot/src/create_rsa_device.php
  iot/src/create_unauth_device.php
  iot/src/delete_device.php
  iot/src/delete_gateway.php
  iot/src/delete_registry.php
  iot/src/get_device.php
  iot/src/get_device_configs.php
  iot/src/get_device_state.php
  iot/src/get_iam_policy.php
  iot/src/get_registry.php
  iot/src/list_devices.php
  iot/src/list_devices_for_gateway.php
  iot/src/list_gateways.php
  iot/src/list_registries.php
  iot/src/patch_es.php
  iot/src/patch_rsa.php
  iot/src/send_command_to_device.php
  iot/src/set_device_config.php
  iot/src/set_device_state.php
  iot/src/set_iam_policy.php
  iot/src/unbind_device_from_gateway.php
  iot/test/iotTest.php
Labels: cla: yes, samples

#1377 chore: compute sample comments and readme updates
  compute/cloud-client/instances/README.md
  compute/cloud-client/instances/src/create_instance.php
  compute/cloud-client/instances/src/delete_instance.php
  compute/cloud-client/instances/src/list_all_instances.php
  compute/cloud-client/instances/src/list_instances.php
Labels: api: compute, automerge, cla: yes, samples

#1378 chore: upgrade IAP samples to new samples format
  iap/README.md
  iap/composer.json
  iap/iap.php
  iap/src/make_iap_request.php
  iap/src/validate_jwt.php
  iap/test/iapTest.php
Labels: cla: yes, samples

#1388 chore: fix link in readme
  appengine/wordpress/README.md
Labels: cla: yes, samples

#1387 fixes(bigtable): Fixes variable casing in Bigtable samples #1385
  bigtable/src/create_cluster.php
  bigtable/src/create_dev_instance.php
  bigtable/src/create_family_gc_intersection.php
  bigtable/src/create_family_gc_max_age.php
  bigtable/src/create_family_gc_max_versions.php
  bigtable/src/create_family_gc_nested.php
  bigtable/src/create_family_gc_union.php
  bigtable/src/create_production_instance.php
  bigtable/src/create_table.php
  bigtable/src/delete_cluster.php
  bigtable/src/delete_family.php
  bigtable/src/delete_instance.php
  bigtable/src/delete_table.php
  bigtable/src/filter_snippets.php
  bigtable/src/hello_world.php
  bigtable/src/insert_update_rows.php
  bigtable/src/list_column_families.php
  bigtable/src/list_instance.php
  bigtable/src/list_instance_clusters.php
  bigtable/src/list_tables.php
  bigtable/src/quickstart.php
  bigtable/src/read_snippets.php
  bigtable/src/update_gc_rule.php
  bigtable/src/writes/write_batch.php
  bigtable/src/writes/write_conditionally.php
  bigtable/src/writes/write_increment.php
  bigtable/src/writes/write_simple.php
Labels: api: bigtable, cla: yes, samples

#1391 chore: ensure different samples get separate PRs for updating deps
  renovate.json
Labels: cla: yes, samples

#1383 feat: Compute Engine sample to present default values behaviour
  CODEOWNERS
  compute/cloud-client/instances/composer.json
  compute/cloud-client/instances/src/set_usage_export_bucket.php
  compute/cloud-client/instances/test/instancesTest.php
  testing/run_test_suite.sh
Labels: api: compute, automerge, cla: yes, samples

#1011 Upgrade Symfony 3.x to 4.4.x
  appengine/flexible/symfony/README.md
  appengine/flexible/symfony/src/AppBundle/EventSubscriber/ExceptionSubscriber.php
  appengine/flexible/symfony/test/DeployTest.php
Labels: automerge, cla: yes, samples

#1400 fix: failing monitoring, dlp, and video samples
  dlp/test/dlpTest.php
  monitoring/test/alertsTest.php
  video/quickstart.php
  video/src/analyze_explicit_content.php
  video/src/analyze_labels_file.php
  video/src/analyze_labels_gcs.php
  video/src/analyze_object_tracking.php
  video/src/analyze_object_tracking_file.php
  video/src/analyze_shots.php
  video/src/analyze_text_detection.php
  video/src/analyze_text_detection_file.php
  video/src/analyze_transcription.php
Labels: cla: yes, samples

#1399 chore: remove job samples
  jobs/README.md
  jobs/composer.json
  jobs/jobs.php
  jobs/phpunit.xml.dist
  jobs/quickstart.php
  jobs/src/auto_complete_sample.php
  jobs/src/basic_company_sample.php
  jobs/src/basic_job_sample.php
  jobs/src/batch_operation_sample.php
  jobs/src/commute_search_sample.php
  jobs/src/custom_attribute_sample.php
  jobs/src/email_alert_search_sample.php
  jobs/src/featured_jobs_search_sample.php
  jobs/src/general_search_sample.php
  jobs/src/histogram_sample.php
  jobs/src/location_search_sample.php
  jobs/src/var_export.php
  jobs/test/AutoCompleteSampleTest.php
  jobs/test/BasicCompanySampleTest.php
  jobs/test/BasicJobSampleTest.php
  jobs/test/BatchOperationSampleTest.php
  jobs/test/CommuteSearchSampleTest.php
  jobs/test/CustomAttributeSampleTest.php
  jobs/test/EmailAlertSearchSampleTest.php
  jobs/test/FeaturedJobsSearchSampleTest.php
  jobs/test/GeneralSearchSampleTest.php
  jobs/test/HistogramSampleTest.php
  jobs/test/LocationSearchSampleTest.php
  testing/run_test_suite.sh
Labels: cla: yes, samples

#1415 fix(deps): update datastore/tutorial to symfony/console to v5
  datastore/tutorial/composer.json
  datastore/tutorial/src/CreateTaskCommand.php
  datastore/tutorial/src/DeleteTaskCommand.php
  datastore/tutorial/src/ListTasksCommand.php
  datastore/tutorial/src/MarkTaskDoneCommand.php
Labels: cla: yes, samples

#1390 chore: ignore appengine/flexible dependencies
  renovate.json
Labels: cla: yes, samples

#1375 chore: upgrade auth samples to latest format
  auth/README.md
  auth/app-flex.yaml
  auth/app-standard.yaml
  auth/app.yaml
  auth/auth.php
  auth/composer.json
  auth/index.php
  auth/src/auth_api_explicit.php
  auth/src/auth_api_explicit_compute.php
  auth/src/auth_api_explicit_compute_engine.php
  auth/src/auth_api_implicit.php
  auth/src/auth_cloud_explicit.php
  auth/src/auth_cloud_explicit_app_engine.php
  auth/src/auth_cloud_explicit_compute.php
  auth/src/auth_cloud_implicit.php
  auth/src/auth_http_explicit.php
  auth/src/auth_http_implicit.php
  auth/test/authTest.php
Labels: cla: yes, samples

#1413 fix: upgrade and fix asset samples
  asset/composer.json
  asset/src/batch_get_assets_history.php
  testing/run_test_suite.sh
Labels: cla: yes, samples

#1420 removes unused test dep
  testing/composer.json
Labels: cla: yes, samples

#1384 chore: upgrade some storage samples
  storage/README.md
  storage/composer.json
  storage/src/add_bucket_acl.php
  storage/src/add_bucket_default_acl.php
  storage/src/add_bucket_label.php
  storage/src/create_bucket.php
  storage/src/delete_bucket.php
  storage/src/delete_bucket_acl.php
  storage/src/delete_bucket_default_acl.php
  storage/src/download_encrypted_object.php
  storage/src/enable_default_kms_key.php
  storage/src/generate_encryption_key.php
  storage/src/get_bucket_acl.php
  storage/src/get_bucket_acl_for_entity.php
  storage/src/get_bucket_default_acl.php
  storage/src/get_bucket_default_acl_for_entity.php
  storage/src/get_bucket_labels.php
  storage/src/get_bucket_metadata.php
  storage/src/list_buckets.php
  storage/src/remove_bucket_label.php
  storage/src/rotate_encryption_key.php
  storage/src/upload_encrypted_object.php
  storage/src/upload_with_kms_key.php
  storage/storage.php
  storage/test/storageTest.php
Labels: cla: yes, samples

#1426 chore: Compute - update comments and variable name based on iX input
  compute/cloud-client/instances/src/set_usage_export_bucket.php
Labels: api: compute, cla: yes, samples

#1427 fix: blunderbuss.yaml
  .github/blunderbuss.yml
Labels: cla: yes, samples

#1339 chore: add blunderbuss config to cloud iot label
  .github/blunderbuss.yml
Labels: automerge, cla: yes, samples

#1428 chore: hopefully fix flakey tests
  functions/helloworld_pubsub/index.php
  monitoring/test/alertsTest.php
  testing/run_test_suite.sh
Labels: cla: yes, samples
