Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2021-07, with the labels that each got.

#1440 chore: Minor error msg change in testing/bootstrap.php
  testing/bootstrap.php
Labels: cla: yes, samples

#1438 feat(spanner): update query option samples with optimizerStatisticsPackage
  spanner/src/create_client_with_query_options.php
  spanner/src/query_data_with_query_options.php
Labels: api: spanner, cla: yes, samples

#1433 Refactoring set, get and disable usage export bucket samples
  compute/cloud-client/instances/README.md
  compute/cloud-client/instances/src/disable_usage_export_bucket.php
  compute/cloud-client/instances/src/get_usage_export_bucket.php
  compute/cloud-client/instances/src/set_usage_export_bucket.php
  compute/cloud-client/instances/test/instancesTest.php
Labels: api: compute, automerge, cla: yes, samples

#1441 feat(spanner): add samples for creating instances with processing units
  spanner/src/create_instance_with_processing_units.php
  spanner/test/spannerTest.php
Labels: api: spanner, cla: yes, samples

#1442 chore: Updating php-cs-fixer config file to support php-cs-fixer 3.0
  .php-cs-fixer.dist.php
  testing/composer.json
  testing/run_cs_check.sh
Labels: cla: yes, samples

#1319 feat(spanner): add CMEK samples
  spanner/src/create_backup_with_encryption_key.php
  spanner/src/create_database_with_encryption_key.php
  spanner/src/restore_backup_with_encryption_key.php
  spanner/test/spannerBackupTest.php
  spanner/test/spannerTest.php
Labels: api: spanner, automerge, cla: yes, samples

#1444 chore: add renovate dependency dashboard and increase PR concurrency
  renovate.json
Labels: cla: yes, samples

#1432 chore: fix dlp trigger tests
  dlp/src/list_jobs.php
  dlp/test/dlpTest.php
Labels: cla: yes, samples

#1446 chore: gives Spanner team owners
  CODEOWNERS
Labels: cla: yes, samples

#1443 chore(tests): ensure test directories use the correct name
  cloud_sql/mysql/pdo/test/IntegrationTest.php
  cloud_sql/mysql/pdo/test/VotesTest.php
  cloud_sql/postgres/pdo/test/IntegrationTest.php
  cloud_sql/postgres/pdo/test/VotesTest.php
  cloud_sql/sqlserver/pdo/test/IntegrationTest.php
  cloud_sql/sqlserver/pdo/test/VotesTest.php
Labels: cla: yes, samples

#1448 Chore: Updated Bigtable 'Create' samples to use the new format
  bigtable/src/create_cluster.php
  bigtable/src/create_dev_instance.php
  bigtable/src/create_family_gc_intersection.php
  bigtable/src/create_family_gc_max_age.php
  bigtable/src/create_family_gc_max_versions.php
  bigtable/src/create_family_gc_nested.php
  bigtable/src/create_family_gc_union.php
  bigtable/src/create_production_instance.php
  bigtable/src/create_table.php
Labels: cla: yes, samples

#1451 chore: Bigtable read_snippets.php split to individual samples in the new format
  bigtable/src/read_filter.php
  bigtable/src/read_prefix.php
  bigtable/src/read_row.php
  bigtable/src/read_row_partial.php
  bigtable/src/read_row_range.php
  bigtable/src/read_row_ranges.php
  bigtable/src/read_rows.php
  bigtable/src/read_snippets.php
  bigtable/test/readTest.php
Labels: cla: yes, samples

#1449 chore: Changed samples in Bigtable to new format for the 'list samples' - issue #1389
  bigtable/src/list_column_families.php
  bigtable/src/list_instance.php
  bigtable/src/list_instance_clusters.php
  bigtable/src/list_tables.php
  bigtable/test/bigtableTest.php
Labels: cla: yes, samples
