Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2021-04, with the labels that each got.

#1330 chore(GAE logging): fix slow tests
  appengine/standard/logging/test/DeployTest.php
Labels: cla: yes, samples

#1323 feat(Kokoro): add sub-directory support + split out lint build
  .kokoro/lint.cfg
  .kokoro/lint.sh
  .kokoro/system_tests.sh
Labels: cla: yes, kokoro:run-all, samples

#1301 feat(functions): add firebase analytics sample
  CODEOWNERS
  functions/firebase_analytics/composer.json
  functions/firebase_analytics/index.php
  functions/firebase_analytics/phpunit.xml.dist
  functions/firebase_analytics/test/IntegrationTest.php
Labels: api: cloudfunctions, cla: yes, samples

#1334 fix: kokoro lint builds and lint script
  .kokoro/lint.cfg
  .kokoro/lint.sh
  .kokoro/php74.cfg
  .kokoro/system_tests.sh
  testing/run_cs_check.sh
Labels: cla: yes, samples

#1335 Revert SUB_DIRECTORY in favor of TEST_DIRECTORIES env var
  .kokoro/system_tests.sh
Labels: cla: yes, samples

#1341 fix: better error handling and cleaner testing for imagemagick sample
  functions/imagemagick/index.php
  functions/imagemagick/test/DeployTest.php
  functions/imagemagick/test/IntegrationTest.php
  functions/imagemagick/test/TestCasesTrait.php
Labels: automerge, cla: yes, samples

#1342 fix: functions retry sample and test
  functions/tips_retry/index.php
  functions/tips_retry/puppies.jpg
  functions/tips_retry/test/DeployTest.php
  functions/tips_retry/test/IntegrationTest.php
Labels: cla: yes, samples

#1340 fix: helloworld pubsub sample
  functions/helloworld_pubsub/index.php
  functions/helloworld_pubsub/test/DeployTest.php
  functions/helloworld_pubsub/test/IntegrationTest.php
Labels: automerge, cla: yes, samples

#1343 fix: functions concepts_requests sample
  functions/concepts_requests/test/DeployTest.php
  functions/concepts_requests/test/SystemTest.php
  functions/concepts_requests/test/TestCasesTrait.php
  functions/concepts_requests/test/UnitTest.php
Labels: cla: yes, samples

#1346 chore: take personal ownership of ML samples
  CODEOWNERS
Labels: cla: yes, samples

#1347 Update PHP to 7.4 in docs and config
  appengine/standard/slim-framework/README.md
  appengine/standard/slim-framework/phpunit.xml.dist
Labels: cla: yes, samples
