Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2021-03, with the labels that each got.

#1293 samples(spanner): PITR samples backup fix
  spanner/src/create_backup.php
  spanner/test/spannerBackupTest.php
Labels: cla: yes, samples

#1294 docs: remove unused region tags
  securitycenter/src/create_notification.php
  securitycenter/src/delete_notification.php
  securitycenter/src/get_notification.php
  securitycenter/src/list_notification.php
  securitycenter/src/update_notification.php
Labels: automerge, cla: yes, samples

#1289 chore(App Engine): switch YAMLs to PHP 7.4
  appengine/standard/auth/app.yaml
  appengine/standard/errorreporting/app.yaml
  appengine/standard/front-controller/app.yaml
  appengine/standard/getting-started/app.yaml
  appengine/standard/grpc/app.yaml
  appengine/standard/helloworld/app.yaml
  appengine/standard/laravel-framework/app.yaml
  appengine/standard/logging/app.yaml
  appengine/standard/memorystore/app.yaml
  appengine/standard/metadata/app.yaml
  appengine/standard/slim-framework/app.yaml
  appengine/standard/storage/app.yaml
  appengine/standard/symfony-framework/app.yaml
  appengine/standard/tasks/apps/handler/app.yaml
  appengine/standard/trace/app.yaml
Labels: api: appengine, cla: yes, samples

#1288 chore(functions): use processFunctionLogs in helper library
  functions/firebase_firestore/test/DeployTest.php
  functions/firebase_remote_config/test/DeployTest.php
  functions/helloworld_pubsub/test/DeployTest.php
  functions/helloworld_storage/test/DeployTest.php
  functions/imagemagick/test/DeployTest.php
  functions/tips_infinite_retries/test/DeployTest.php
  functions/tips_retry/test/DeployTest.php
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1297 feat(functions): add Pub/Sub test examples
  functions/helloworld_pubsub/SampleIntegrationTest.php
  functions/helloworld_pubsub/SampleUnitTest.php
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1292 feat(functions): add Firestore reactive sample
  functions/firebase_firestore_reactive/composer.json
  functions/firebase_firestore_reactive/index.php
  functions/firebase_firestore_reactive/php.ini
  functions/firebase_firestore_reactive/phpunit.xml.dist
  functions/firebase_firestore_reactive/test/DeployTest.php
  functions/firebase_firestore_reactive/test/IntegrationTest.php
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1224 feat(functions): add Firebase RTDB sample
  functions/firebase_rtdb/composer.json
  functions/firebase_rtdb/index.php
  functions/firebase_rtdb/phpunit.xml.dist
  functions/firebase_rtdb/test/DeployTest.php
  functions/firebase_rtdb/test/IntegrationTest.php
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1277 chore: remove cloud run button from eventarc generic README
  eventarc/generic/README.md
Labels: cla: yes, samples

#1300 chore: add region tags for logger import
  appengine/flexible/logging/app.php
Labels: cla: yes, samples

#1303 chore: removed unsupported samples
  vision/composer.json
  vision/src/detect_crop_hints.php
  vision/src/detect_crop_hints_gcs.php
  vision/test/visionTest.php
  vision/vision.php
Labels: cla: yes, samples

#1298 fix(functions/http_content_type): PHP warning when header doesn't exist
  functions/http_content_type/index.php
  functions/slack_slash_command/index.php
Labels: api: cloudfunctions, cla: yes, samples

#1306 chore: removed unsupport vision product search samples
  vision/composer.json
  vision/product_search.php
  vision/src/product_create.php
  vision/src/product_delete.php
  vision/src/product_get.php
  vision/src/product_image_create.php
  vision/src/product_image_delete.php
  vision/src/product_image_get.php
  vision/src/product_image_list.php
  vision/src/product_list.php
  vision/src/product_purge_orphan_products.php
  vision/src/product_purge_products_in_product_set.php
  vision/src/product_search_similar.php
  vision/src/product_search_similar_gcs.php
  vision/src/product_set_add_product.php
  vision/src/product_set_create.php
  vision/src/product_set_delete.php
  vision/src/product_set_get.php
  vision/src/product_set_import.php
  vision/src/product_set_list.php
  vision/src/product_set_list_products.php
  vision/src/product_set_remove_product.php
  vision/src/product_update.php
  vision/test/data/shoes_1.jpg
  vision/test/data/shoes_2.jpg
  vision/test/productSearchTest.php
Labels: cla: yes, samples

#1305 feat(compute): add cloud-client compute sample
  compute/helloworld/README.md
  compute/helloworld/api-client/README.md
  compute/helloworld/api-client/app.php
  compute/helloworld/api-client/composer.json
  compute/helloworld/cloud-client/README.md
  compute/helloworld/cloud-client/app.php
  compute/helloworld/cloud-client/composer.json
Labels: api: compute, cla: yes, samples

#1311 fix(asset): sample warnings, upgrade to new snippet format
  asset/asset.php
  asset/composer.json
  asset/src/batch_get_assets_history.php
  asset/src/export_assets.php
  asset/src/search_all_iam_policies.php
  asset/src/search_all_resources.php
  asset/test/assetSearchTest.php
  asset/test/assetTest.php
  testing/sample_helpers.php
Labels: api: cloudasset, cla: yes, samples

#1314 fix: misc functions sample changes
  functions/helloworld_http/SampleUnitTest.php
  functions/helloworld_pubsub/index.php
  functions/tips_infinite_retries/index.php
  functions/tips_retry/index.php
Labels: cla: yes, samples

#1274 docs: add a sample for the Data API v1 beta
  .kokoro/secrets-example.sh
  .kokoro/secrets.sh.enc
  analyticsdata/README.md
  analyticsdata/composer.json
  analyticsdata/quickstart.php
  analyticsdata/quickstart_json_credentials.php
  analyticsdata/quickstart_oauth2/README.md
  analyticsdata/quickstart_oauth2/composer.json
  analyticsdata/quickstart_oauth2/index.php
  analyticsdata/test/quickstartJsonCredentialsTest.php
  analyticsdata/test/quickstartTest.php
Labels: cla: yes, samples

#1321 fix: kms test namespace
  kms/test/kmsTest.php
Labels: cla: yes, samples

#1320 feat: add deploy group
  appengine/standard/auth/test/DeployTest.php
  appengine/standard/errorreporting/test/DeployTest.php
  appengine/standard/front-controller/test/DeployTest.php
  appengine/standard/getting-started/test/DeployTest.php
  appengine/standard/grpc/test/DeployTest.php
  appengine/standard/helloworld/test/DeployTest.php
  appengine/standard/laravel-framework/test/DeployDatabaseTest.php
  appengine/standard/laravel-framework/test/DeployStackdriverTest.php
  appengine/standard/laravel-framework/test/DeployTest.php
  appengine/standard/logging/test/DeployTest.php
  appengine/standard/memorystore/test/DeployTest.php
  appengine/standard/metadata/test/DeployTest.php
  appengine/standard/slim-framework/test/DeployTest.php
  appengine/standard/storage/test/DeployTest.php
  appengine/standard/symfony-framework/test/DeployDoctrineTest.php
  appengine/standard/symfony-framework/test/DeployTest.php
  appengine/standard/tasks/apps/handler/test/DeployTest.php
  appengine/standard/trace/test/DeployTest.php
  appengine/standard/wordpress/test/DeployTest.php
  endpoints/getting-started/test/DeployTest.php
  eventarc/generic/test/DeployTest.php
  functions/concepts_filesystem/test/DeployTest.php
  functions/concepts_requests/test/DeployTest.php
  functions/env_vars/test/DeployTest.php
  functions/firebase_firestore/test/DeployTest.php
  functions/firebase_firestore_reactive/test/DeployTest.php
  functions/firebase_remote_config/test/DeployTest.php
  functions/firebase_rtdb/test/DeployTest.php
  functions/helloworld_get/test/DeployTest.php
  functions/helloworld_http/test/DeployTest.php
  functions/helloworld_log/test/DeployTest.php
  functions/helloworld_pubsub/test/DeployTest.php
  functions/helloworld_storage/test/DeployTest.php
  functions/http_content_type/test/DeployTest.php
  functions/http_cors/test/DeployTest.php
  functions/http_form_data/test/DeployTest.php
  functions/http_method/test/DeployTest.php
  functions/imagemagick/test/DeployTest.php
  functions/slack_slash_command/test/DeployTest.php
  functions/tips_infinite_retries/test/DeployTest.php
  functions/tips_phpinfo/test/DeployTest.php
  functions/tips_retry/test/DeployTest.php
  functions/tips_scopes/test/DeployTest.php
  pubsub/app/phpunit.xml.dist
  run/helloworld/test/DeployTest.php
Labels: cla: yes, samples
