Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2022-10, with the labels that each got.

#1693 feat(Storage): Added sample to print bucket website configuration
  storage/src/print_bucket_website_configuration.php
  storage/test/storageTest.php
Labels: api: storage, samples

#1678 fix(functions): add 2nd-gen cloudevent tags
  functions/helloworld_pubsub/SampleUnitTest.php
  functions/helloworld_pubsub/index.php
  functions/helloworld_storage/SampleUnitTest.php
  functions/helloworld_storage/index.php
Labels: api: cloudfunctions, samples

#1699 Dml batch update request priority
  spanner/src/dml_batch_update_request_priority.php
  spanner/test/spannerTest.php
Labels: samples
