Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2022-05, with the labels that each got.

#1622 Attempt to fix Renovate Configuration - issue #1545
  renovate.json
Labels: type: bug, samples

#1624 feat(Compute): Compute suspend/resume samples
  compute/cloud-client/instances/src/create_instance.php
  compute/cloud-client/instances/src/create_instance_with_encryption_key.php
  compute/cloud-client/instances/src/resume_instance.php
  compute/cloud-client/instances/src/suspend_instance.php
  compute/cloud-client/instances/test/instancesTest.php
Labels: api: compute, samples

#1631 Firestore - Adding a warning to enable indexing before querying collection group
  firestore/src/query_collection_group_filter_eq.php
Labels: samples

#1634 docs: add Google Cloud Samples browser link to readme template
  README.md
Labels: samples

#1644 fix: phpstan lint errors
  auth/src/auth_api_explicit.php
  auth/src/auth_api_explicit_compute.php
  auth/src/auth_api_implicit.php
  monitoring/src/create_metric.php
  monitoring/src/read_timeseries_align.php
  monitoring/src/read_timeseries_fields.php
  monitoring/src/read_timeseries_reduce.php
  monitoring/src/read_timeseries_simple.php
Labels: samples

#1641 chore: upgrade texttospeech to new sample format
  texttospeech/src/list_voices.php
  texttospeech/src/synthesize_ssml.php
  texttospeech/src/synthesize_ssml_file.php
  texttospeech/src/synthesize_text.php
  texttospeech/src/synthesize_text_effects_profile.php
  texttospeech/src/synthesize_text_effects_profile_file.php
  texttospeech/src/synthesize_text_file.php
  texttospeech/test/textToSpeechTest.php
Labels: samples
