Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2022-04, with the labels that each got.

#1609 chore(functions/helloworld_storage): clarify comments
  functions/helloworld_storage/index.php
Labels: api: cloudfunctions, samples

#1612 chore: add missing readmes for functions samples
  functions/README.md
  functions/concepts_build_extension/README.md
  functions/concepts_filesystem/README.md
  functions/concepts_requests/README.md
  functions/env_vars/README.md
  functions/firebase_analytics/README.md
  functions/firebase_auth/README.md
  functions/firebase_firestore/README.md
  functions/firebase_firestore_reactive/README.md
  functions/firebase_remote_config/README.md
  functions/firebase_rtdb/README.md
  functions/helloworld_get/README.md
  functions/helloworld_http/README.md
  functions/helloworld_log/README.md
  functions/helloworld_pubsub/README.md
  functions/helloworld_storage/README.md
  functions/http_content_type/README.md
  functions/http_cors/README.md
  functions/http_form_data/README.md
  functions/http_method/README.md
  functions/slack_slash_command/README.md
  functions/tips_infinite_retries/README.md
  functions/tips_phpinfo/README.md
  functions/tips_retry/README.md
  functions/tips_scopes/README.md
Labels: samples

#1588 chore: fix typos, use doublequotes in shell scripts
  logging/README.md
  testing/run_cs_check.sh
Labels: samples

#1608 Adding a sample to set storage endpoint
  storage/src/set_client_endpoint.php
  storage/test/storageTest.php
Labels: api: storage, samples

#1616 Adding samples for printing bucket/object ACLs
  storage/src/print_bucket_acl_for_user.php
  storage/src/print_file_acl_for_user.php
  storage/test/ObjectAclTest.php
Labels: samples

#1615 chore: update DLP samples to new sample format
  dlp/src/categorical_stats.php
  dlp/src/create_inspect_template.php
  dlp/src/create_trigger.php
  dlp/src/deidentify_dates.php
  dlp/src/deidentify_fpe.php
  dlp/src/deidentify_mask.php
  dlp/src/delete_inspect_template.php
  dlp/src/delete_job.php
  dlp/src/delete_trigger.php
  dlp/src/inspect_bigquery.php
  dlp/src/inspect_datastore.php
  dlp/src/inspect_gcs.php
  dlp/src/inspect_image_file.php
  dlp/src/inspect_string.php
  dlp/src/inspect_text_file.php
  dlp/src/k_anonymity.php
  dlp/src/k_map.php
  dlp/src/l_diversity.php
  dlp/src/list_info_types.php
  dlp/src/list_inspect_templates.php
  dlp/src/list_jobs.php
  dlp/src/list_triggers.php
  dlp/src/numerical_stats.php
  dlp/src/redact_image.php
  dlp/src/reidentify_fpe.php
  dlp/test/dlpLongRunningTest.php
  dlp/test/dlpTest.php
  testing/sample_helpers.php
Labels: samples
