Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2022-08, with the labels that each got.

#1613 feat: update all runtimes to new PHP 8.1 runtime
  appengine/standard/auth/app.yaml
  appengine/standard/extensions/app.yaml
  appengine/standard/front-controller/app.yaml
  appengine/standard/getting-started/app.yaml
  appengine/standard/grpc/index.php
  appengine/standard/helloworld/app.yaml
  appengine/standard/laravel-framework/app-dbsessions.yaml
  appengine/standard/laravel-framework/app.yaml
  appengine/standard/logging/app.yaml
  appengine/standard/memorystore/app.yaml
  appengine/standard/metadata/app.yaml
  appengine/standard/slim-framework/README.md
  appengine/standard/slim-framework/app.yaml
  appengine/standard/tasks/apps/handler/app.yaml
  appengine/standard/trace/app.yaml
  functions/firebase_firestore/composer.json
  functions/firebase_firestore/php.ini
  functions/firebase_firestore_reactive/composer.json
  pubsub/app/app.yaml
Labels: samples

#1666 chore: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: samples

#1649 chore: upgrade KMS to new sample format
  kms/src/create_key_asymmetric_decrypt.php
  kms/src/create_key_asymmetric_sign.php
  kms/src/create_key_hsm.php
  kms/src/create_key_labels.php
  kms/src/create_key_mac.php
  kms/src/create_key_ring.php
  kms/src/create_key_rotation_schedule.php
  kms/src/create_key_symmetric_encrypt_decrypt.php
  kms/src/create_key_version.php
  kms/src/decrypt_asymmetric.php
  kms/src/decrypt_symmetric.php
  kms/src/destroy_key_version.php
  kms/src/disable_key_version.php
  kms/src/enable_key_version.php
  kms/src/encrypt_asymmetric.php
  kms/src/encrypt_symmetric.php
  kms/src/generate_random_bytes.php
  kms/src/get_key_labels.php
  kms/src/get_key_version_attestation.php
  kms/src/get_public_key.php
  kms/src/iam_add_member.php
  kms/src/iam_get_policy.php
  kms/src/iam_remove_member.php
  kms/src/quickstart.php
  kms/src/restore_key_version.php
  kms/src/sign_asymmetric.php
  kms/src/sign_mac.php
  kms/src/update_key_add_rotation.php
  kms/src/update_key_remove_labels.php
  kms/src/update_key_remove_rotation.php
  kms/src/update_key_set_primary.php
  kms/src/update_key_update_labels.php
  kms/src/verify_asymmetric_ec.php
  kms/src/verify_asymmetric_rsa.php
  kms/src/verify_mac.php
  kms/test/kmsTest.php
  testing/sample_helpers.php
Labels: type: cleanup, samples

#1664 docs(secretmanager): Added sample for creating Secret with UserManaged replication
  secretmanager/src/create_secret_with_user_managed_replication.php
  secretmanager/test/secretmanagerTest.php
Labels: api: secretmanager, samples

#1646 Create update_secret_with_alias.php
  secretmanager/src/update_secret_with_alias.php
  secretmanager/test/secretmanagerTest.php
Labels: samples

#1669 refactor(storage): Update Dual-Region Bucket Creation Metadata
  storage/src/create_bucket_dual_region.php
  storage/test/storageTest.php
Labels: api: storage, samples

#1672 feat(PubSub): Added samples for Exactly Once Delivery
  pubsub/api/src/create_subscription_with_exactly_once_delivery.php
  pubsub/api/src/subscribe_exactly_once_delivery.php
  pubsub/api/test/pubsubTest.php
Labels: api: pubsub, samples

#1675 chore(PubSub): Bump google/cloud-pubsub in composer.json
  pubsub/api/composer.json
Labels: api: pubsub, samples

#1671 samples: add new sample for analytics data api
  analyticsdata/run_report.php
  analyticsdata/test/runReportTest.php
Labels: samples

#1677 chore: add style guide to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: samples
