Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2023-05, with the labels that each got.

#1813 chore(Pubsub): Fix Avro samples (Publish and Subscribe)
  pubsub/api/src/publish_avro_records.php
  pubsub/api/src/subscribe_avro_records.php
  pubsub/api/test/SchemaTest.php
Labels: api: pubsub, samples

#1819 Added sample for DLP : Inspect a string for sensitive data, excluding a custom substring
  dlp/src/inspect_string_custom_excluding_substring.php
  dlp/test/dlpTest.php
Labels: samples

#1818 Added sample for DLP : Inspect a string, excluding REGEX matches
  dlp/src/inspect_string_with_exclusion_regex.php
  dlp/test/dlpTest.php
Labels: samples

#1822 feat(pubsub): publish with retrySettings
  pubsub/api/src/publish_with_retry_settings.php
  pubsub/api/test/pubsubTest.php
Labels: api: pubsub, samples

#1825 Added sample for DLP : De-identify sensitive data to replacing matched input values.
  dlp/src/deidentify_replace.php
  dlp/test/dlpTest.php
Labels: samples

#1837 Added sample for DLP : De-identify Table Samples
  dlp/src/deidentify_table_bucketing.php
  dlp/src/deidentify_table_condition_infotypes.php
  dlp/src/deidentify_table_condition_masking.php
  dlp/src/deidentify_table_infotypes.php
  dlp/src/deidentify_table_row_suppress.php
  dlp/test/data/table1.csv
  dlp/test/data/table2.csv
  dlp/test/dlpTest.php
Labels: samples

#1838 chore: upgrade to PHP 8.1 and PHP 8.2, drop support for PHP 7.4 and below
  .kokoro/deploy_gae.cfg
  .kokoro/deploy_gcf.cfg
  .kokoro/deploy_misc.cfg
  .kokoro/php81.cfg
  .kokoro/php82.cfg
  .kokoro/php_rest.cfg
  .kokoro/system_tests.sh
  appengine/standard/errorreporting/README.md
  appengine/standard/errorreporting/app.yaml
  appengine/standard/errorreporting/composer.json
  appengine/standard/errorreporting/index.php
  appengine/standard/errorreporting/php.ini
  appengine/standard/grpc/README.md
  appengine/standard/grpc/app.yaml
  appengine/standard/memorystore/test/DeployTest.php
  appengine/standard/symfony-framework/app.yaml
  asset/src/export_assets.php
  asset/test/assetSearchTest.php
  asset/test/assetTest.php
  auth/app.yaml
  bigtable/src/create_cluster.php
  bigtable/src/create_cluster_autoscale_config.php
  bigtable/src/disable_cluster_autoscale_config.php
  bigtable/src/update_cluster_autoscale_config.php
  cloud_sql/mysql/pdo/app.standard.yaml
  cloud_sql/mysql/pdo/test/IntegrationTest.php
  cloud_sql/mysql/pdo/test/VotesTest.php
  cloud_sql/postgres/pdo/app.standard.yaml
  cloud_sql/postgres/pdo/test/IntegrationTest.php
  cloud_sql/postgres/pdo/test/VotesTest.php
  cloud_sql/sqlserver/pdo/test/IntegrationTest.php
  cloud_sql/sqlserver/pdo/test/VotesTest.php
  compute/firewall/src/create_firewall_rule.php
  compute/firewall/src/delete_firewall_rule.php
  compute/firewall/src/patch_firewall_priority.php
  compute/instances/src/create_instance.php
  compute/instances/src/create_instance_with_encryption_key.php
  compute/instances/src/delete_instance.php
  compute/instances/src/disable_usage_export_bucket.php
  compute/instances/src/reset_instance.php
  compute/instances/src/resume_instance.php
  compute/instances/src/set_usage_export_bucket.php
  compute/instances/src/start_instance.php
  compute/instances/src/start_instance_with_encryption_key.php
  compute/instances/src/stop_instance.php
  compute/instances/src/suspend_instance.php
  compute/instances/test/instancesTest.php
  dlp/README.md
  dlp/test/dlpLongRunningTest.php
  dlp/test/dlpTest.php
  language/test/quickstartTest.php
  logging/test/loggingTest.php
  media/transcoder/test/transcoderTest.php
  pubsub/api/test/pubsubTest.php
  servicedirectory/README.md
  spanner/test/spannerBackupTest.php
  storage/test/storageTest.php
  storagetransfer/test/StorageTransferTest.php
  testing/composer.json
Labels: samples

#1811 feat(Pubsub): Add samples for ordering keys
  pubsub/api/src/enable_subscription_ordering.php
  pubsub/api/src/publish_with_ordering_keys.php
  pubsub/api/test/pubsubTest.php
Labels: api: pubsub, samples

#1845 feat(PubSub): Added Samples
  pubsub/api/src/commit_avro_schema.php
  pubsub/api/src/commit_proto_schema.php
  pubsub/api/src/get_schema_revision.php
  pubsub/api/src/list_schema_revisions.php
  pubsub/api/test/SchemaTest.php
Labels: api: pubsub, samples

#1850 chore(endpoints): Update region tag with product prefix
  endpoints/getting-started/app.yaml
Labels: samples, api: endpoints

#1849 Added sample for DLP : Inspect info types samples
  dlp/src/inspect_augment_infotypes.php
  dlp/src/inspect_column_values_w_custom_hotwords.php
  dlp/src/inspect_image_all_infotypes.php
  dlp/src/inspect_image_listed_infotypes.php
  dlp/src/inspect_table.php
  dlp/test/dlpTest.php
Labels: samples

#1851 Added sample for DLP : Redact data from image files
  dlp/src/redact_image_all_infotypes.php
  dlp/src/redact_image_all_text.php
  dlp/src/redact_image_colored_infotypes.php
  dlp/src/redact_image_listed_infotypes.php
  dlp/test/dlpTest.php
Labels: samples

#1824 Added sample for DLP : Inspect a string from sensitive data by using a custom hotword
  dlp/src/inspect_string_custom_hotword.php
  dlp/test/dlpTest.php
Labels: samples
