Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2023-10, with the labels that each got.

#1925 chore: fix lint github action
  .github/workflows/lint.yml
  testing/run_staticanalysis_check.sh
Labels: samples

#1924 fix(dlp):Corrected the region tags
  dlp/src/inspect_text_file.php
  dlp/src/k_anonymity.php
Labels: api: dlp, samples

#1874 feat(PubSub): Add CPS to GCS sample
  .kokoro/secrets.sh.enc
  pubsub/api/composer.json
  pubsub/api/src/create_cloud_storage_subscription.php
  pubsub/api/test/pubsubTest.php
Labels: api: pubsub, samples

#1927 fix: deprecate assertRegexp usage over assertMatchesRegularExpression
  appengine/flexible/metadata/test/DeployTest.php
  monitoring/test/alertsTest.php
  pubsub/api/test/pubsubTest.php
  speech/test/speechTest.php
  storage/test/IamTest.php
  vision/test/visionTest.php
Labels: samples

#1930 fix: Dlp static method classnames
  dlp/src/deidentify_cloud_storage.php
Labels: samples

#1933 fix: correct phpunit config for run/laravel
  run/laravel/phpunit.xml
  run/laravel/tests/CreatesApplication.php
  run/laravel/tests/Feature/LandingPageTest.php
  run/laravel/tests/Feature/ProductTest.php
  run/laravel/tests/TestCase.php
Labels: samples

#1931 chore(b-230113499): remove beta references from jobs
  run/laravel/README.md
Labels: samples

#1935 chore(samples): removing iot samples
  .kokoro/secrets-example.sh
  .kokoro/secrets.sh.enc
  iot/composer.json
  iot/phpunit.xml.dist.deprecated
  iot/src/bind_device_to_gateway.php
  iot/src/create_es_device.php
  iot/src/create_gateway.php
  iot/src/create_registry.php
  iot/src/create_rsa_device.php
  iot/src/create_unauth_device.php
  iot/src/delete_device.php
  iot/src/delete_gateway.php
  iot/src/delete_registry.php
  iot/src/get_device.php
  iot/src/get_device_configs.php
  iot/src/get_device_state.php
  iot/src/get_iam_policy.php
  iot/src/get_registry.php
  iot/src/list_devices.php
  iot/src/list_devices_for_gateway.php
  iot/src/list_gateways.php
  iot/src/list_registries.php
  iot/src/patch_es.php
  iot/src/patch_rsa.php
  iot/src/send_command_to_device.php
  iot/src/set_device_config.php
  iot/src/set_device_state.php
  iot/src/set_iam_policy.php
  iot/src/unbind_device_from_gateway.php
  iot/test/data/ec_public.pem
  iot/test/data/rsa_cert.pem
  iot/test/iotTest.php.deprecated
  testing/run_staticanalysis_check.sh
  testing/run_test_suite.sh
Labels: samples

#1928 feat(Storage): Update samples to showcase Storage Autoclass V2 usage
  storage/src/get_bucket_autoclass.php
  storage/src/set_bucket_autoclass.php
  storage/test/storageTest.php
Labels: api: storage, samples
