Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2023-06, with the labels that each got.

#1829 feat: update secretmanager to new (beta) v2gapic surface
  secretmanager/src/access_secret_version.php
  secretmanager/src/add_secret_version.php
  secretmanager/src/create_secret.php
  secretmanager/src/create_secret_with_user_managed_replication.php
  secretmanager/src/delete_secret.php
  secretmanager/src/destroy_secret_version.php
  secretmanager/src/disable_secret_version.php
  secretmanager/src/enable_secret_version.php
  secretmanager/src/get_secret.php
  secretmanager/src/get_secret_version.php
  secretmanager/src/iam_grant_access.php
  secretmanager/src/iam_revoke_access.php
  secretmanager/src/list_secret_versions.php
  secretmanager/src/list_secrets.php
  secretmanager/src/update_secret.php
  secretmanager/src/update_secret_with_alias.php
Labels: samples

#1848 Added sample for DLP : Create and get job
  dlp/src/create_job.php
  dlp/src/get_job.php
  dlp/test/dlpTest.php
Labels: samples

#1852 Added sample for DLP : De-identify and re-identify samples
  dlp/src/deidentify_deterministic.php
  dlp/src/deidentify_free_text_with_fpe_using_surrogate.php
  dlp/src/deidentify_table_fpe.php
  dlp/src/reidentify_deterministic.php
  dlp/src/reidentify_free_text_with_fpe_using_surrogate.php
  dlp/src/reidentify_table_fpe.php
  dlp/src/reidentify_text_fpe.php
  dlp/test/data/fpe_input.csv
  dlp/test/dlpTest.php
Labels: samples

#1793 feat(Spanner): add sample for update database
  spanner/composer.json
  spanner/src/update_database.php
  spanner/test/spannerTest.php
Labels: api: spanner, samples

#1853 chore(Spanner): Update batch_query_data sample
  spanner/src/batch_query_data.php
Labels: api: spanner, samples

#1840 chore: remove dollar outside curly braces
  appengine/flexible/drupal8/test/DeployTest.php
  appengine/flexible/laravel/test/DeployDatabaseSessionTest.php
  appengine/flexible/symfony/test/DeployTest.php
  appengine/standard/getting-started/src/app.php
  appengine/standard/getting-started/test/CloudSqlTest.php
  cloud_sql/mysql/pdo/test/IntegrationTest.php
  cloud_sql/postgres/pdo/test/IntegrationTest.php
Labels: samples

#1855 chore(docs): remove archived tutorial samples
  appengine/standard/README.md
  appengine/standard/wordpress/.gitignore
  appengine/standard/wordpress/README.md
  appengine/standard/wordpress/composer.json
  appengine/standard/wordpress/phpunit.xml.dist
  appengine/standard/wordpress/test/DeployTest.php
  appengine/wordpress/README.md
Labels: wordpress, api: appengine, samples
