Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2023-08, with the labels that each got.

#1905 chore: retire IoT samples
  CODEOWNERS
  iot/README.md
  iot/phpunit.xml.dist.deprecated
  iot/test/iotTest.php.deprecated
Labels: samples

#1836 feat(Spanner): Add bit reversed sequence samples
  spanner/src/alter_sequence.php
  spanner/src/create_sequence.php
  spanner/src/drop_sequence.php
  spanner/src/pg_alter_sequence.php
  spanner/src/pg_create_sequence.php
  spanner/src/pg_drop_sequence.php
  spanner/test/spannerPgTest.php
  spanner/test/spannerTest.php
Labels: api: spanner, samples

#1892 feat(Transcoder): add batch mode sample and test
  media/transcoder/composer.json
  media/transcoder/src/create_job_from_preset_batch_mode.php
  media/transcoder/test/transcoderTest.php
Labels: samples, api: transcoder

#1909 feat(Live Stream): add samples and tests for assets and pools
  media/livestream/composer.json
  media/livestream/src/create_asset.php
  media/livestream/src/delete_asset.php
  media/livestream/src/get_asset.php
  media/livestream/src/get_pool.php
  media/livestream/src/list_assets.php
  media/livestream/src/update_pool.php
  media/livestream/test/livestreamTest.php
Labels: samples, api: livestream

#1866 feat(functions): create new samples for typed function signature
  functions/typed_greeting/composer.json
  functions/typed_greeting/index.php
  functions/typed_greeting/phpunit.xml.dist
  functions/typed_greeting/test/UnitTest.php
Labels: api: cloudfunctions, samples

#1901 feat: initial commit of run mc php nginx sample
  run/README.md
  run/multi-container/hello-php-nginx-sample/README.md
  run/multi-container/hello-php-nginx-sample/composer.json
  run/multi-container/hello-php-nginx-sample/nginx/Dockerfile
  run/multi-container/hello-php-nginx-sample/nginx/index.php
  run/multi-container/hello-php-nginx-sample/nginx/nginx.conf
  run/multi-container/hello-php-nginx-sample/php-app/Dockerfile
  run/multi-container/hello-php-nginx-sample/php-app/index.php
  run/multi-container/hello-php-nginx-sample/php-app/opcache.ini
  run/multi-container/hello-php-nginx-sample/phpunit.xml.dist
  run/multi-container/hello-php-nginx-sample/service.yaml
  run/multi-container/hello-php-nginx-sample/test/TestCase.php
Labels: samples

#1913 fix: updates cloud run mc php nginx sample
  run/multi-container/hello-php-nginx-sample/README.md
  run/multi-container/hello-php-nginx-sample/php-app/Dockerfile
  run/multi-container/hello-php-nginx-sample/php-app/opcache.ini
  run/multi-container/hello-php-nginx-sample/service.yaml
Labels: samples

#1912 chore: update code owners to infra-db-sdk
  .github/blunderbuss.yml
  CODEOWNERS
Labels: samples

#1835 feat(dlp): sample for Inspect BigQuery for sensitive data with sampling
  dlp/src/inspect_bigquery_with_sampling.php
  dlp/test/dlpLongRunningTest.php
  dlp/test/dlpTest.php
Labels: api: dlp, samples
