Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2024-01, with the labels that each got.

#1952 chore: upgrade spanner samples to new client surface
  spanner/composer.json
  spanner/src/enable_fine_grained_access.php
  spanner/src/list_database_roles.php
Labels: samples

#1951 chore: upgrade dialogflow samples to new client surface
  dialogflow/composer.json
  dialogflow/dialogflow.php
  dialogflow/src/context_create.php
  dialogflow/src/context_delete.php
  dialogflow/src/context_list.php
  dialogflow/src/detect_intent_audio.php
  dialogflow/src/detect_intent_stream.php
  dialogflow/src/detect_intent_texts.php
  dialogflow/src/entity_create.php
  dialogflow/src/entity_delete.php
  dialogflow/src/entity_list.php
  dialogflow/src/entity_type_create.php
  dialogflow/src/entity_type_delete.php
  dialogflow/src/entity_type_list.php
  dialogflow/src/intent_create.php
  dialogflow/src/intent_delete.php
  dialogflow/src/intent_list.php
  dialogflow/src/session_entity_type_create.php
  dialogflow/src/session_entity_type_delete.php
  dialogflow/src/session_entity_type_list.php
Labels: samples

#1946 chore: upgrade secretmanager samples to new client surface
  dialogflow/composer.json
  recaptcha/composer.json
  secretmanager/composer.json
  secretmanager/quickstart.php
  secretmanager/test/quickstartTest.php
  secretmanager/test/secretmanagerTest.php
Labels: samples

#1903 chore: upgrade TextToSpeech samples to new surface
  texttospeech/composer.json
  texttospeech/quickstart.php
  texttospeech/src/list_voices.php
  texttospeech/src/synthesize_ssml.php
  texttospeech/src/synthesize_ssml_file.php
  texttospeech/src/synthesize_text.php
  texttospeech/src/synthesize_text_effects_profile.php
  texttospeech/src/synthesize_text_effects_profile_file.php
  texttospeech/src/synthesize_text_file.php
Labels: samples, new surface

#1895 chore: upgrade asset samples to new surface
  asset/composer.json
  asset/src/batch_get_assets_history.php
  asset/src/export_assets.php
  asset/src/list_assets.php
  asset/src/search_all_iam_policies.php
  asset/src/search_all_resources.php
Labels: samples, new surface

#1896 chore: upgrade compute samples to new surface
  compute/firewall/composer.json
  compute/firewall/src/create_firewall_rule.php
  compute/firewall/src/delete_firewall_rule.php
  compute/firewall/src/list_firewall_rules.php
  compute/firewall/src/patch_firewall_priority.php
  compute/firewall/src/print_firewall_rule.php
  compute/helloworld/app.php
  compute/helloworld/composer.json
  compute/instances/composer.json
  compute/instances/src/create_instance.php
  compute/instances/src/create_instance_with_encryption_key.php
  compute/instances/src/delete_instance.php
  compute/instances/src/disable_usage_export_bucket.php
  compute/instances/src/get_usage_export_bucket.php
  compute/instances/src/list_all_images.php
  compute/instances/src/list_all_instances.php
  compute/instances/src/list_images_by_page.php
  compute/instances/src/list_instances.php
  compute/instances/src/reset_instance.php
  compute/instances/src/resume_instance.php
  compute/instances/src/set_usage_export_bucket.php
  compute/instances/src/start_instance.php
  compute/instances/src/start_instance_with_encryption_key.php
  compute/instances/src/stop_instance.php
  compute/instances/src/suspend_instance.php
Labels: samples, new surface

#1883 chore: upgrade translate samples to new surface
  translate/composer.json
  translate/src/v3_batch_translate_text.php
  translate/src/v3_batch_translate_text_with_glossary.php
  translate/src/v3_batch_translate_text_with_glossary_and_model.php
  translate/src/v3_batch_translate_text_with_model.php
  translate/src/v3_create_glossary.php
  translate/src/v3_delete_glossary.php
  translate/src/v3_detect_language.php
  translate/src/v3_get_glossary.php
  translate/src/v3_get_supported_languages.php
  translate/src/v3_get_supported_languages_for_target.php
  translate/src/v3_list_glossary.php
  translate/src/v3_translate_text.php
  translate/src/v3_translate_text_with_glossary.php
  translate/src/v3_translate_text_with_glossary_and_model.php
  translate/src/v3_translate_text_with_model.php
  translate/test/translateTest.php
Labels: samples, new surface

#1939 feat(Spanner): Add directed read samples
  spanner/src/directed_read.php
  spanner/test/spannerTest.php
Labels: api: spanner, samples

#1881 chore: upgrade tasks samples to new surface
  tasks/composer.json
  tasks/src/create_http_task.php
  tasks/src/create_http_task_with_token.php
Labels: samples, new surface

#1882 chore: upgrade storagetransfer samples to new surface
  storagetransfer/composer.json
  storagetransfer/src/quickstart.php
  storagetransfer/test/StorageTransferTest.php
Labels: samples, new surface

#1950 chore: upgrade kms samples to new client surface
  kms/composer.json
  kms/src/create_key_asymmetric_decrypt.php
  kms/src/create_key_asymmetric_sign.php
  kms/src/create_key_hsm.php
  kms/src/create_key_labels.php
  kms/src/create_key_mac.php
  kms/src/create_key_ring.php
  kms/src/create_key_rotation_schedule.php
  kms/src/create_key_symmetric_encrypt_decrypt.php
  kms/src/create_key_version.php
  kms/src/decrypt_asymmetric.php
  kms/src/decrypt_symmetric.php
  kms/src/destroy_key_version.php
  kms/src/disable_key_version.php
  kms/src/enable_key_version.php
  kms/src/encrypt_symmetric.php
  kms/src/generate_random_bytes.php
  kms/src/get_key_labels.php
  kms/src/get_key_version_attestation.php
  kms/src/get_public_key.php
  kms/src/iam_add_member.php
  kms/src/iam_get_policy.php
  kms/src/iam_remove_member.php
  kms/src/quickstart.php
  kms/src/restore_key_version.php
  kms/src/sign_asymmetric.php
  kms/src/sign_mac.php
  kms/src/update_key_add_rotation.php
  kms/src/update_key_remove_labels.php
  kms/src/update_key_remove_rotation.php
  kms/src/update_key_set_primary.php
  kms/src/update_key_update_labels.php
  kms/src/verify_asymmetric_ec.php
  kms/src/verify_mac.php
  kms/test/kmsTest.php
Labels: samples, new surface

#1947 chore: upgrade securitycenter samples to new client surface
  securitycenter/composer.json
  securitycenter/src/create_notification.php
  securitycenter/src/delete_notification.php
  securitycenter/src/get_notification.php
  securitycenter/src/list_notification.php
  securitycenter/src/update_notification.php
Labels: samples, new surface

#1949 chore: upgrade monitoring samples to new client surface
  monitoring/composer.json
  monitoring/quickstart.php
  monitoring/src/alert_backup_policies.php
  monitoring/src/alert_create_channel.php
  monitoring/src/alert_create_policy.php
  monitoring/src/alert_delete_channel.php
  monitoring/src/alert_enable_policies.php
  monitoring/src/alert_list_channels.php
  monitoring/src/alert_list_policies.php
  monitoring/src/alert_replace_channels.php
  monitoring/src/alert_restore_policies.php
  monitoring/src/create_metric.php
  monitoring/src/create_uptime_check.php
  monitoring/src/delete_metric.php
  monitoring/src/delete_uptime_check.php
  monitoring/src/get_descriptor.php
  monitoring/src/get_resource.php
  monitoring/src/get_uptime_check.php
  monitoring/src/list_descriptors.php
  monitoring/src/list_resources.php
  monitoring/src/list_uptime_check_ips.php
  monitoring/src/list_uptime_checks.php
  monitoring/src/read_timeseries_align.php
  monitoring/src/read_timeseries_fields.php
  monitoring/src/read_timeseries_reduce.php
  monitoring/src/read_timeseries_simple.php
  monitoring/src/update_uptime_check.php
  monitoring/src/write_timeseries.php
  monitoring/test/alertsTest.php
Labels: samples, new surface
