Repository GoogleCloudPlatform/php-docs-samples, pull requests merged in 2024-07, with the labels that each got.

#2019 chore: Update some PHP GAE Flex samples to use newer runtimes
  appengine/flexible/datastore/app.yaml
  appengine/flexible/helloworld/app.yaml
  appengine/flexible/storage/app.yaml
Labels: samples

#2021 chore: upgrade storageinsights to new surface
  storageinsights/composer.json
  storageinsights/src/create_inventory_report_config.php
  storageinsights/src/delete_inventory_report_config.php
  storageinsights/src/edit_inventory_report_config.php
  storageinsights/src/get_inventory_report_names.php
  storageinsights/src/list_inventory_report_configs.php
Labels: samples

#2022 Chore: update wordpress for GAE flex
  appengine/flexible/wordpress/files/app.yaml
  appengine/flexible/wordpress/files/nginx-app.conf
  appengine/flexible/wordpress/files/php.ini
Labels: samples

#2030 Chore: update GAE flex websockets to use newer runtimes.
  appengine/flexible/websockets/additional-supervisord.conf
  appengine/flexible/websockets/app.yaml
  appengine/flexible/websockets/nginx-app.conf
  appengine/flexible/websockets/nginx.conf
Labels: samples

#2029 feat(Firestore): add sample for multiple inequality filters
  firestore/src/query_filter_compound_multi_ineq.php
  firestore/src/query_order_field_invalid.php
  firestore/test/firestoreTest.php
Labels: api: firestore, samples

#2033 chore: refactor datastore samples
  datastore/api/src/ancestor_query.php
  datastore/api/src/array_value.php
  datastore/api/src/array_value_equality.php
  datastore/api/src/array_value_inequality_range.php
  datastore/api/src/ascending_sort.php
  datastore/api/src/basic_entity.php
  datastore/api/src/basic_gql_query.php
  datastore/api/src/basic_query.php
  datastore/api/src/batch_delete.php
  datastore/api/src/batch_lookup.php
  datastore/api/src/batch_upsert.php
  datastore/api/src/composite_filter.php
  datastore/api/src/cursor_paging.php
  datastore/api/src/delete.php
  datastore/api/src/descending_sort.php
  datastore/api/src/distinct_on.php
  datastore/api/src/entity_with_parent.php
  datastore/api/src/equal_and_inequality_range.php
  datastore/api/src/eventual_consistent_query.php
  datastore/api/src/exploding_properties.php
  datastore/api/src/get_or_create.php
  datastore/api/src/get_task_list_entities.php
  datastore/api/src/incomplete_key.php
  datastore/api/src/inequality_invalid.php
  datastore/api/src/inequality_range.php
  datastore/api/src/inequality_sort.php
  datastore/api/src/inequality_sort_invalid_not_first.php
  datastore/api/src/inequality_sort_invalid_not_same.php
  datastore/api/src/insert.php
  datastore/api/src/key_filter.php
  datastore/api/src/key_with_multilevel_parent.php
  datastore/api/src/key_with_parent.php
  datastore/api/src/keys_only_query.php
  datastore/api/src/kind_run_query.php
  datastore/api/src/kindless_query.php
  datastore/api/src/limit.php
  datastore/api/src/lookup.php
  datastore/api/src/multi_sort.php
  datastore/api/src/named_key.php
  datastore/api/src/namespace_run_query.php
  datastore/api/src/projection_query.php
  datastore/api/src/properties.php
  datastore/api/src/property_by_kind_run_query.php
  datastore/api/src/property_filter.php
  datastore/api/src/property_filtering_run_query.php
  datastore/api/src/property_run_query.php
  datastore/api/src/run_projection_query.php
  datastore/api/src/run_query.php
  datastore/api/src/transactional_retry.php
  datastore/api/src/transfer_funds.php
  datastore/api/src/unindexed_property_query.php
  datastore/api/src/update.php
  datastore/api/src/upsert.php
  datastore/api/test/ConceptsTest.php
Labels: samples

#2034 feat(Datastore): add samples for multiple inequality
  datastore/api/src/query_filter_compound_multi_ineq.php
  datastore/api/test/ConceptsTest.php
Labels: api: datastore, samples

#2036 chore: update firestore ineq sample to use cities
  firestore/src/data_get_dataset.php
  firestore/src/query_filter_compound_multi_ineq.php
  firestore/src/query_filter_dataset.php
  firestore/test/firestoreTest.php
Labels: samples

#2037 feat(spanner): add samples for instance partitions
  spanner/src/create_instance_partition.php
  spanner/test/spannerTest.php
Labels: api: spanner, samples

#2038 chore: update region tag for query_filter_compound_multi_ineq.php
  firestore/src/query_filter_compound_multi_ineq.php
Labels: samples
